// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: finevision/compute/v1/artifact.proto

package computev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ArtifactDescriptor struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ArtifactId       string                 `protobuf:"bytes,1,opt,name=artifact_id,json=artifactId,proto3" json:"artifact_id,omitempty"`
	ArtifactType     string                 `protobuf:"bytes,2,opt,name=artifact_type,json=artifactType,proto3" json:"artifact_type,omitempty"`
	Uri              string                 `protobuf:"bytes,3,opt,name=uri,proto3" json:"uri,omitempty"`
	Sha256           string                 `protobuf:"bytes,4,opt,name=sha256,proto3" json:"sha256,omitempty"`
	SizeBytes        int64                  `protobuf:"varint,5,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	ContentType      string                 `protobuf:"bytes,6,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	StorageVersion   string                 `protobuf:"bytes,7,opt,name=storage_version,json=storageVersion,proto3" json:"storage_version,omitempty"`
	Producer         string                 `protobuf:"bytes,8,opt,name=producer,proto3" json:"producer,omitempty"`
	DatasetVersionId string                 `protobuf:"bytes,9,opt,name=dataset_version_id,json=datasetVersionId,proto3" json:"dataset_version_id,omitempty"`
	TrainingRunId    string                 `protobuf:"bytes,10,opt,name=training_run_id,json=trainingRunId,proto3" json:"training_run_id,omitempty"`
	AttemptId        string                 `protobuf:"bytes,11,opt,name=attempt_id,json=attemptId,proto3" json:"attempt_id,omitempty"`
	SchemaVersion    int32                  `protobuf:"varint,12,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	CreatedAt        *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	VerifiedAt       *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=verified_at,json=verifiedAt,proto3" json:"verified_at,omitempty"`
	Metadata         *structpb.Struct       `protobuf:"bytes,15,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ArtifactDescriptor) Reset() {
	*x = ArtifactDescriptor{}
	mi := &file_finevision_compute_v1_artifact_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArtifactDescriptor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArtifactDescriptor) ProtoMessage() {}

func (x *ArtifactDescriptor) ProtoReflect() protoreflect.Message {
	mi := &file_finevision_compute_v1_artifact_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArtifactDescriptor.ProtoReflect.Descriptor instead.
func (*ArtifactDescriptor) Descriptor() ([]byte, []int) {
	return file_finevision_compute_v1_artifact_proto_rawDescGZIP(), []int{0}
}

func (x *ArtifactDescriptor) GetArtifactId() string {
	if x != nil {
		return x.ArtifactId
	}
	return ""
}

func (x *ArtifactDescriptor) GetArtifactType() string {
	if x != nil {
		return x.ArtifactType
	}
	return ""
}

func (x *ArtifactDescriptor) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

func (x *ArtifactDescriptor) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

func (x *ArtifactDescriptor) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *ArtifactDescriptor) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *ArtifactDescriptor) GetStorageVersion() string {
	if x != nil {
		return x.StorageVersion
	}
	return ""
}

func (x *ArtifactDescriptor) GetProducer() string {
	if x != nil {
		return x.Producer
	}
	return ""
}

func (x *ArtifactDescriptor) GetDatasetVersionId() string {
	if x != nil {
		return x.DatasetVersionId
	}
	return ""
}

func (x *ArtifactDescriptor) GetTrainingRunId() string {
	if x != nil {
		return x.TrainingRunId
	}
	return ""
}

func (x *ArtifactDescriptor) GetAttemptId() string {
	if x != nil {
		return x.AttemptId
	}
	return ""
}

func (x *ArtifactDescriptor) GetSchemaVersion() int32 {
	if x != nil {
		return x.SchemaVersion
	}
	return 0
}

func (x *ArtifactDescriptor) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ArtifactDescriptor) GetVerifiedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.VerifiedAt
	}
	return nil
}

func (x *ArtifactDescriptor) GetMetadata() *structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

var File_finevision_compute_v1_artifact_proto protoreflect.FileDescriptor

const file_finevision_compute_v1_artifact_proto_rawDesc = "" +
	"\n" +
	"$finevision/compute/v1/artifact.proto\x12\x15finevision.compute.v1\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd4\x04\n" +
	"\x12ArtifactDescriptor\x12\x1f\n" +
	"\vartifact_id\x18\x01 \x01(\tR\n" +
	"artifactId\x12#\n" +
	"\rartifact_type\x18\x02 \x01(\tR\fartifactType\x12\x10\n" +
	"\x03uri\x18\x03 \x01(\tR\x03uri\x12\x16\n" +
	"\x06sha256\x18\x04 \x01(\tR\x06sha256\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x05 \x01(\x03R\tsizeBytes\x12!\n" +
	"\fcontent_type\x18\x06 \x01(\tR\vcontentType\x12'\n" +
	"\x0fstorage_version\x18\a \x01(\tR\x0estorageVersion\x12\x1a\n" +
	"\bproducer\x18\b \x01(\tR\bproducer\x12,\n" +
	"\x12dataset_version_id\x18\t \x01(\tR\x10datasetVersionId\x12&\n" +
	"\x0ftraining_run_id\x18\n" +
	" \x01(\tR\rtrainingRunId\x12\x1d\n" +
	"\n" +
	"attempt_id\x18\v \x01(\tR\tattemptId\x12%\n" +
	"\x0eschema_version\x18\f \x01(\x05R\rschemaVersion\x129\n" +
	"\n" +
	"created_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12;\n" +
	"\vverified_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"verifiedAt\x123\n" +
	"\bmetadata\x18\x0f \x01(\v2\x17.google.protobuf.StructR\bmetadataBXZVgithub.com/tianyuqic1/FGVCplateformPublic/go/api/proto/finevision/compute/v1;computev1b\x06proto3"

var (
	file_finevision_compute_v1_artifact_proto_rawDescOnce sync.Once
	file_finevision_compute_v1_artifact_proto_rawDescData []byte
)

func file_finevision_compute_v1_artifact_proto_rawDescGZIP() []byte {
	file_finevision_compute_v1_artifact_proto_rawDescOnce.Do(func() {
		file_finevision_compute_v1_artifact_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_finevision_compute_v1_artifact_proto_rawDesc), len(file_finevision_compute_v1_artifact_proto_rawDesc)))
	})
	return file_finevision_compute_v1_artifact_proto_rawDescData
}

var file_finevision_compute_v1_artifact_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_finevision_compute_v1_artifact_proto_goTypes = []any{
	(*ArtifactDescriptor)(nil),    // 0: finevision.compute.v1.ArtifactDescriptor
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
	(*structpb.Struct)(nil),       // 2: google.protobuf.Struct
}
var file_finevision_compute_v1_artifact_proto_depIdxs = []int32{
	1, // 0: finevision.compute.v1.ArtifactDescriptor.created_at:type_name -> google.protobuf.Timestamp
	1, // 1: finevision.compute.v1.ArtifactDescriptor.verified_at:type_name -> google.protobuf.Timestamp
	2, // 2: finevision.compute.v1.ArtifactDescriptor.metadata:type_name -> google.protobuf.Struct
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_finevision_compute_v1_artifact_proto_init() }
func file_finevision_compute_v1_artifact_proto_init() {
	if File_finevision_compute_v1_artifact_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_finevision_compute_v1_artifact_proto_rawDesc), len(file_finevision_compute_v1_artifact_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_finevision_compute_v1_artifact_proto_goTypes,
		DependencyIndexes: file_finevision_compute_v1_artifact_proto_depIdxs,
		MessageInfos:      file_finevision_compute_v1_artifact_proto_msgTypes,
	}.Build()
	File_finevision_compute_v1_artifact_proto = out.File
	file_finevision_compute_v1_artifact_proto_goTypes = nil
	file_finevision_compute_v1_artifact_proto_depIdxs = nil
}
