// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: finevision/compute/v1/inference_runtime.proto

package computev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PredictRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	ModelBundle   *ArtifactDescriptor    `protobuf:"bytes,2,opt,name=model_bundle,json=modelBundle,proto3" json:"model_bundle,omitempty"`
	InputImage    *ArtifactDescriptor    `protobuf:"bytes,3,opt,name=input_image,json=inputImage,proto3" json:"input_image,omitempty"`
	Policy        *structpb.Struct       `protobuf:"bytes,4,opt,name=policy,proto3" json:"policy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PredictRequest) Reset() {
	*x = PredictRequest{}
	mi := &file_finevision_compute_v1_inference_runtime_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PredictRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PredictRequest) ProtoMessage() {}

func (x *PredictRequest) ProtoReflect() protoreflect.Message {
	mi := &file_finevision_compute_v1_inference_runtime_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PredictRequest.ProtoReflect.Descriptor instead.
func (*PredictRequest) Descriptor() ([]byte, []int) {
	return file_finevision_compute_v1_inference_runtime_proto_rawDescGZIP(), []int{0}
}

func (x *PredictRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *PredictRequest) GetModelBundle() *ArtifactDescriptor {
	if x != nil {
		return x.ModelBundle
	}
	return nil
}

func (x *PredictRequest) GetInputImage() *ArtifactDescriptor {
	if x != nil {
		return x.InputImage
	}
	return nil
}

func (x *PredictRequest) GetPolicy() *structpb.Struct {
	if x != nil {
		return x.Policy
	}
	return nil
}

type Prediction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TopK          []*LabelScore          `protobuf:"bytes,1,rep,name=top_k,json=topK,proto3" json:"top_k,omitempty"`
	Decision      string                 `protobuf:"bytes,2,opt,name=decision,proto3" json:"decision,omitempty"`
	Confidence    float64                `protobuf:"fixed64,3,opt,name=confidence,proto3" json:"confidence,omitempty"`
	Margin        float64                `protobuf:"fixed64,4,opt,name=margin,proto3" json:"margin,omitempty"`
	OodScore      float64                `protobuf:"fixed64,5,opt,name=ood_score,json=oodScore,proto3" json:"ood_score,omitempty"`
	Reasons       []string               `protobuf:"bytes,6,rep,name=reasons,proto3" json:"reasons,omitempty"`
	Evidence      *structpb.Struct       `protobuf:"bytes,7,opt,name=evidence,proto3" json:"evidence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Prediction) Reset() {
	*x = Prediction{}
	mi := &file_finevision_compute_v1_inference_runtime_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Prediction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Prediction) ProtoMessage() {}

func (x *Prediction) ProtoReflect() protoreflect.Message {
	mi := &file_finevision_compute_v1_inference_runtime_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Prediction.ProtoReflect.Descriptor instead.
func (*Prediction) Descriptor() ([]byte, []int) {
	return file_finevision_compute_v1_inference_runtime_proto_rawDescGZIP(), []int{1}
}

func (x *Prediction) GetTopK() []*LabelScore {
	if x != nil {
		return x.TopK
	}
	return nil
}

func (x *Prediction) GetDecision() string {
	if x != nil {
		return x.Decision
	}
	return ""
}

func (x *Prediction) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *Prediction) GetMargin() float64 {
	if x != nil {
		return x.Margin
	}
	return 0
}

func (x *Prediction) GetOodScore() float64 {
	if x != nil {
		return x.OodScore
	}
	return 0
}

func (x *Prediction) GetReasons() []string {
	if x != nil {
		return x.Reasons
	}
	return nil
}

func (x *Prediction) GetEvidence() *structpb.Struct {
	if x != nil {
		return x.Evidence
	}
	return nil
}

type LabelScore struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Label         string                 `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	Score         float64                `protobuf:"fixed64,2,opt,name=score,proto3" json:"score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LabelScore) Reset() {
	*x = LabelScore{}
	mi := &file_finevision_compute_v1_inference_runtime_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LabelScore) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LabelScore) ProtoMessage() {}

func (x *LabelScore) ProtoReflect() protoreflect.Message {
	mi := &file_finevision_compute_v1_inference_runtime_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LabelScore.ProtoReflect.Descriptor instead.
func (*LabelScore) Descriptor() ([]byte, []int) {
	return file_finevision_compute_v1_inference_runtime_proto_rawDescGZIP(), []int{2}
}

func (x *LabelScore) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *LabelScore) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

type EvictCacheRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sha256        string                 `protobuf:"bytes,1,opt,name=sha256,proto3" json:"sha256,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvictCacheRequest) Reset() {
	*x = EvictCacheRequest{}
	mi := &file_finevision_compute_v1_inference_runtime_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvictCacheRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvictCacheRequest) ProtoMessage() {}

func (x *EvictCacheRequest) ProtoReflect() protoreflect.Message {
	mi := &file_finevision_compute_v1_inference_runtime_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvictCacheRequest.ProtoReflect.Descriptor instead.
func (*EvictCacheRequest) Descriptor() ([]byte, []int) {
	return file_finevision_compute_v1_inference_runtime_proto_rawDescGZIP(), []int{3}
}

func (x *EvictCacheRequest) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

type EvictCacheResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Evicted       bool                   `protobuf:"varint,1,opt,name=evicted,proto3" json:"evicted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvictCacheResponse) Reset() {
	*x = EvictCacheResponse{}
	mi := &file_finevision_compute_v1_inference_runtime_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvictCacheResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvictCacheResponse) ProtoMessage() {}

func (x *EvictCacheResponse) ProtoReflect() protoreflect.Message {
	mi := &file_finevision_compute_v1_inference_runtime_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvictCacheResponse.ProtoReflect.Descriptor instead.
func (*EvictCacheResponse) Descriptor() ([]byte, []int) {
	return file_finevision_compute_v1_inference_runtime_proto_rawDescGZIP(), []int{4}
}

func (x *EvictCacheResponse) GetEvicted() bool {
	if x != nil {
		return x.Evicted
	}
	return false
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_finevision_compute_v1_inference_runtime_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_finevision_compute_v1_inference_runtime_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_finevision_compute_v1_inference_runtime_proto_rawDescGZIP(), []int{5}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_finevision_compute_v1_inference_runtime_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_finevision_compute_v1_inference_runtime_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_finevision_compute_v1_inference_runtime_proto_rawDescGZIP(), []int{6}
}

func (x *HealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_finevision_compute_v1_inference_runtime_proto protoreflect.FileDescriptor

const file_finevision_compute_v1_inference_runtime_proto_rawDesc = "" +
	"\n" +
	"-finevision/compute/v1/inference_runtime.proto\x12\x15finevision.compute.v1\x1a$finevision/compute/v1/artifact.proto\x1a\x1cgoogle/protobuf/struct.proto\"\xfa\x01\n" +
	"\x0ePredictRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12L\n" +
	"\fmodel_bundle\x18\x02 \x01(\v2).finevision.compute.v1.ArtifactDescriptorR\vmodelBundle\x12J\n" +
	"\vinput_image\x18\x03 \x01(\v2).finevision.compute.v1.ArtifactDescriptorR\n" +
	"inputImage\x12/\n" +
	"\x06policy\x18\x04 \x01(\v2\x17.google.protobuf.StructR\x06policy\"\x84\x02\n" +
	"\n" +
	"Prediction\x126\n" +
	"\x05top_k\x18\x01 \x03(\v2!.finevision.compute.v1.LabelScoreR\x04topK\x12\x1a\n" +
	"\bdecision\x18\x02 \x01(\tR\bdecision\x12\x1e\n" +
	"\n" +
	"confidence\x18\x03 \x01(\x01R\n" +
	"confidence\x12\x16\n" +
	"\x06margin\x18\x04 \x01(\x01R\x06margin\x12\x1b\n" +
	"\tood_score\x18\x05 \x01(\x01R\boodScore\x12\x18\n" +
	"\areasons\x18\x06 \x03(\tR\areasons\x123\n" +
	"\bevidence\x18\a \x01(\v2\x17.google.protobuf.StructR\bevidence\"8\n" +
	"\n" +
	"LabelScore\x12\x14\n" +
	"\x05label\x18\x01 \x01(\tR\x05label\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x01R\x05score\"+\n" +
	"\x11EvictCacheRequest\x12\x16\n" +
	"\x06sha256\x18\x01 \x01(\tR\x06sha256\".\n" +
	"\x12EvictCacheResponse\x12\x18\n" +
	"\aevicted\x18\x01 \x01(\bR\aevicted\"\x0f\n" +
	"\rHealthRequest\"(\n" +
	"\x0eHealthResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status2\xa1\x02\n" +
	"\x10InferenceRuntime\x12S\n" +
	"\aPredict\x12%.finevision.compute.v1.PredictRequest\x1a!.finevision.compute.v1.Prediction\x12a\n" +
	"\n" +
	"EvictCache\x12(.finevision.compute.v1.EvictCacheRequest\x1a).finevision.compute.v1.EvictCacheResponse\x12U\n" +
	"\x06Health\x12$.finevision.compute.v1.HealthRequest\x1a%.finevision.compute.v1.HealthResponseBXZVgithub.com/tianyuqic1/FGVCplateformPublic/go/api/proto/finevision/compute/v1;computev1b\x06proto3"

var (
	file_finevision_compute_v1_inference_runtime_proto_rawDescOnce sync.Once
	file_finevision_compute_v1_inference_runtime_proto_rawDescData []byte
)

func file_finevision_compute_v1_inference_runtime_proto_rawDescGZIP() []byte {
	file_finevision_compute_v1_inference_runtime_proto_rawDescOnce.Do(func() {
		file_finevision_compute_v1_inference_runtime_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_finevision_compute_v1_inference_runtime_proto_rawDesc), len(file_finevision_compute_v1_inference_runtime_proto_rawDesc)))
	})
	return file_finevision_compute_v1_inference_runtime_proto_rawDescData
}

var file_finevision_compute_v1_inference_runtime_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_finevision_compute_v1_inference_runtime_proto_goTypes = []any{
	(*PredictRequest)(nil),     // 0: finevision.compute.v1.PredictRequest
	(*Prediction)(nil),         // 1: finevision.compute.v1.Prediction
	(*LabelScore)(nil),         // 2: finevision.compute.v1.LabelScore
	(*EvictCacheRequest)(nil),  // 3: finevision.compute.v1.EvictCacheRequest
	(*EvictCacheResponse)(nil), // 4: finevision.compute.v1.EvictCacheResponse
	(*HealthRequest)(nil),      // 5: finevision.compute.v1.HealthRequest
	(*HealthResponse)(nil),     // 6: finevision.compute.v1.HealthResponse
	(*ArtifactDescriptor)(nil), // 7: finevision.compute.v1.ArtifactDescriptor
	(*structpb.Struct)(nil),    // 8: google.protobuf.Struct
}
var file_finevision_compute_v1_inference_runtime_proto_depIdxs = []int32{
	7, // 0: finevision.compute.v1.PredictRequest.model_bundle:type_name -> finevision.compute.v1.ArtifactDescriptor
	7, // 1: finevision.compute.v1.PredictRequest.input_image:type_name -> finevision.compute.v1.ArtifactDescriptor
	8, // 2: finevision.compute.v1.PredictRequest.policy:type_name -> google.protobuf.Struct
	2, // 3: finevision.compute.v1.Prediction.top_k:type_name -> finevision.compute.v1.LabelScore
	8, // 4: finevision.compute.v1.Prediction.evidence:type_name -> google.protobuf.Struct
	0, // 5: finevision.compute.v1.InferenceRuntime.Predict:input_type -> finevision.compute.v1.PredictRequest
	3, // 6: finevision.compute.v1.InferenceRuntime.EvictCache:input_type -> finevision.compute.v1.EvictCacheRequest
	5, // 7: finevision.compute.v1.InferenceRuntime.Health:input_type -> finevision.compute.v1.HealthRequest
	1, // 8: finevision.compute.v1.InferenceRuntime.Predict:output_type -> finevision.compute.v1.Prediction
	4, // 9: finevision.compute.v1.InferenceRuntime.EvictCache:output_type -> finevision.compute.v1.EvictCacheResponse
	6, // 10: finevision.compute.v1.InferenceRuntime.Health:output_type -> finevision.compute.v1.HealthResponse
	8, // [8:11] is the sub-list for method output_type
	5, // [5:8] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_finevision_compute_v1_inference_runtime_proto_init() }
func file_finevision_compute_v1_inference_runtime_proto_init() {
	if File_finevision_compute_v1_inference_runtime_proto != nil {
		return
	}
	file_finevision_compute_v1_artifact_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_finevision_compute_v1_inference_runtime_proto_rawDesc), len(file_finevision_compute_v1_inference_runtime_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_finevision_compute_v1_inference_runtime_proto_goTypes,
		DependencyIndexes: file_finevision_compute_v1_inference_runtime_proto_depIdxs,
		MessageInfos:      file_finevision_compute_v1_inference_runtime_proto_msgTypes,
	}.Build()
	File_finevision_compute_v1_inference_runtime_proto = out.File
	file_finevision_compute_v1_inference_runtime_proto_goTypes = nil
	file_finevision_compute_v1_inference_runtime_proto_depIdxs = nil
}
