// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.35.1
// source: finevision/compute/v1/inference_runtime.proto

package computev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	InferenceRuntime_Predict_FullMethodName    = "/finevision.compute.v1.InferenceRuntime/Predict"
	InferenceRuntime_EvictCache_FullMethodName = "/finevision.compute.v1.InferenceRuntime/EvictCache"
	InferenceRuntime_Health_FullMethodName     = "/finevision.compute.v1.InferenceRuntime/Health"
)

// InferenceRuntimeClient is the client API for InferenceRuntime service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type InferenceRuntimeClient interface {
	Predict(ctx context.Context, in *PredictRequest, opts ...grpc.CallOption) (*Prediction, error)
	EvictCache(ctx context.Context, in *EvictCacheRequest, opts ...grpc.CallOption) (*EvictCacheResponse, error)
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
}

type inferenceRuntimeClient struct {
	cc grpc.ClientConnInterface
}

func NewInferenceRuntimeClient(cc grpc.ClientConnInterface) InferenceRuntimeClient {
	return &inferenceRuntimeClient{cc}
}

func (c *inferenceRuntimeClient) Predict(ctx context.Context, in *PredictRequest, opts ...grpc.CallOption) (*Prediction, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Prediction)
	err := c.cc.Invoke(ctx, InferenceRuntime_Predict_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inferenceRuntimeClient) EvictCache(ctx context.Context, in *EvictCacheRequest, opts ...grpc.CallOption) (*EvictCacheResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EvictCacheResponse)
	err := c.cc.Invoke(ctx, InferenceRuntime_EvictCache_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inferenceRuntimeClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, InferenceRuntime_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InferenceRuntimeServer is the server API for InferenceRuntime service.
// All implementations must embed UnimplementedInferenceRuntimeServer
// for forward compatibility.
type InferenceRuntimeServer interface {
	Predict(context.Context, *PredictRequest) (*Prediction, error)
	EvictCache(context.Context, *EvictCacheRequest) (*EvictCacheResponse, error)
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	mustEmbedUnimplementedInferenceRuntimeServer()
}

// UnimplementedInferenceRuntimeServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedInferenceRuntimeServer struct{}

func (UnimplementedInferenceRuntimeServer) Predict(context.Context, *PredictRequest) (*Prediction, error) {
	return nil, status.Error(codes.Unimplemented, "method Predict not implemented")
}
func (UnimplementedInferenceRuntimeServer) EvictCache(context.Context, *EvictCacheRequest) (*EvictCacheResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EvictCache not implemented")
}
func (UnimplementedInferenceRuntimeServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedInferenceRuntimeServer) mustEmbedUnimplementedInferenceRuntimeServer() {}
func (UnimplementedInferenceRuntimeServer) testEmbeddedByValue()                          {}

// UnsafeInferenceRuntimeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InferenceRuntimeServer will
// result in compilation errors.
type UnsafeInferenceRuntimeServer interface {
	mustEmbedUnimplementedInferenceRuntimeServer()
}

func RegisterInferenceRuntimeServer(s grpc.ServiceRegistrar, srv InferenceRuntimeServer) {
	// If the following call panics, it indicates UnimplementedInferenceRuntimeServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&InferenceRuntime_ServiceDesc, srv)
}

func _InferenceRuntime_Predict_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PredictRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InferenceRuntimeServer).Predict(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InferenceRuntime_Predict_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InferenceRuntimeServer).Predict(ctx, req.(*PredictRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InferenceRuntime_EvictCache_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EvictCacheRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InferenceRuntimeServer).EvictCache(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InferenceRuntime_EvictCache_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InferenceRuntimeServer).EvictCache(ctx, req.(*EvictCacheRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InferenceRuntime_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InferenceRuntimeServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InferenceRuntime_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InferenceRuntimeServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// InferenceRuntime_ServiceDesc is the grpc.ServiceDesc for InferenceRuntime service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InferenceRuntime_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "finevision.compute.v1.InferenceRuntime",
	HandlerType: (*InferenceRuntimeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Predict",
			Handler:    _InferenceRuntime_Predict_Handler,
		},
		{
			MethodName: "EvictCache",
			Handler:    _InferenceRuntime_EvictCache_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _InferenceRuntime_Health_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "finevision/compute/v1/inference_runtime.proto",
}
