// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.35.1
// source: finevision/compute/v1/model_export.proto

package computev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	structpb "google.golang.org/protobuf/types/known/structpb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ModelExport_ExportHead_FullMethodName = "/finevision.compute.v1.ModelExport/ExportHead"
)

// ModelExportClient is the client API for ModelExport service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ModelExportClient interface {
	ExportHead(ctx context.Context, in *ExportHeadRequest, opts ...grpc.CallOption) (*structpb.Struct, error)
}

type modelExportClient struct {
	cc grpc.ClientConnInterface
}

func NewModelExportClient(cc grpc.ClientConnInterface) ModelExportClient {
	return &modelExportClient{cc}
}

func (c *modelExportClient) ExportHead(ctx context.Context, in *ExportHeadRequest, opts ...grpc.CallOption) (*structpb.Struct, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(structpb.Struct)
	err := c.cc.Invoke(ctx, ModelExport_ExportHead_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ModelExportServer is the server API for ModelExport service.
// All implementations must embed UnimplementedModelExportServer
// for forward compatibility.
type ModelExportServer interface {
	ExportHead(context.Context, *ExportHeadRequest) (*structpb.Struct, error)
	mustEmbedUnimplementedModelExportServer()
}

// UnimplementedModelExportServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedModelExportServer struct{}

func (UnimplementedModelExportServer) ExportHead(context.Context, *ExportHeadRequest) (*structpb.Struct, error) {
	return nil, status.Error(codes.Unimplemented, "method ExportHead not implemented")
}
func (UnimplementedModelExportServer) mustEmbedUnimplementedModelExportServer() {}
func (UnimplementedModelExportServer) testEmbeddedByValue()                     {}

// UnsafeModelExportServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ModelExportServer will
// result in compilation errors.
type UnsafeModelExportServer interface {
	mustEmbedUnimplementedModelExportServer()
}

func RegisterModelExportServer(s grpc.ServiceRegistrar, srv ModelExportServer) {
	// If the following call panics, it indicates UnimplementedModelExportServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ModelExport_ServiceDesc, srv)
}

func _ModelExport_ExportHead_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExportHeadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModelExportServer).ExportHead(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModelExport_ExportHead_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModelExportServer).ExportHead(ctx, req.(*ExportHeadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ModelExport_ServiceDesc is the grpc.ServiceDesc for ModelExport service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ModelExport_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "finevision.compute.v1.ModelExport",
	HandlerType: (*ModelExportServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ExportHead",
			Handler:    _ModelExport_ExportHead_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "finevision/compute/v1/model_export.proto",
}
