// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: finevision/compute/v1/model_export.proto

package computev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExportHeadRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ModelVersionId   string                 `protobuf:"bytes,1,opt,name=model_version_id,json=modelVersionId,proto3" json:"model_version_id,omitempty"`
	DatasetVersionId string                 `protobuf:"bytes,2,opt,name=dataset_version_id,json=datasetVersionId,proto3" json:"dataset_version_id,omitempty"`
	TrainingRunId    string                 `protobuf:"bytes,3,opt,name=training_run_id,json=trainingRunId,proto3" json:"training_run_id,omitempty"`
	SourceBundle     *ArtifactDescriptor    `protobuf:"bytes,4,opt,name=source_bundle,json=sourceBundle,proto3" json:"source_bundle,omitempty"`
	Precision        string                 `protobuf:"bytes,5,opt,name=precision,proto3" json:"precision,omitempty"` // FP32 (default for old clients) or FP16
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ExportHeadRequest) Reset() {
	*x = ExportHeadRequest{}
	mi := &file_finevision_compute_v1_model_export_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportHeadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportHeadRequest) ProtoMessage() {}

func (x *ExportHeadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_finevision_compute_v1_model_export_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportHeadRequest.ProtoReflect.Descriptor instead.
func (*ExportHeadRequest) Descriptor() ([]byte, []int) {
	return file_finevision_compute_v1_model_export_proto_rawDescGZIP(), []int{0}
}

func (x *ExportHeadRequest) GetModelVersionId() string {
	if x != nil {
		return x.ModelVersionId
	}
	return ""
}

func (x *ExportHeadRequest) GetDatasetVersionId() string {
	if x != nil {
		return x.DatasetVersionId
	}
	return ""
}

func (x *ExportHeadRequest) GetTrainingRunId() string {
	if x != nil {
		return x.TrainingRunId
	}
	return ""
}

func (x *ExportHeadRequest) GetSourceBundle() *ArtifactDescriptor {
	if x != nil {
		return x.SourceBundle
	}
	return nil
}

func (x *ExportHeadRequest) GetPrecision() string {
	if x != nil {
		return x.Precision
	}
	return ""
}

var File_finevision_compute_v1_model_export_proto protoreflect.FileDescriptor

const file_finevision_compute_v1_model_export_proto_rawDesc = "" +
	"\n" +
	"(finevision/compute/v1/model_export.proto\x12\x15finevision.compute.v1\x1a$finevision/compute/v1/artifact.proto\x1a\x1cgoogle/protobuf/struct.proto\"\x81\x02\n" +
	"\x11ExportHeadRequest\x12(\n" +
	"\x10model_version_id\x18\x01 \x01(\tR\x0emodelVersionId\x12,\n" +
	"\x12dataset_version_id\x18\x02 \x01(\tR\x10datasetVersionId\x12&\n" +
	"\x0ftraining_run_id\x18\x03 \x01(\tR\rtrainingRunId\x12N\n" +
	"\rsource_bundle\x18\x04 \x01(\v2).finevision.compute.v1.ArtifactDescriptorR\fsourceBundle\x12\x1c\n" +
	"\tprecision\x18\x05 \x01(\tR\tprecision2^\n" +
	"\vModelExport\x12O\n" +
	"\n" +
	"ExportHead\x12(.finevision.compute.v1.ExportHeadRequest\x1a\x17.google.protobuf.StructBXZVgithub.com/tianyuqic1/FGVCplateformPublic/go/api/proto/finevision/compute/v1;computev1b\x06proto3"

var (
	file_finevision_compute_v1_model_export_proto_rawDescOnce sync.Once
	file_finevision_compute_v1_model_export_proto_rawDescData []byte
)

func file_finevision_compute_v1_model_export_proto_rawDescGZIP() []byte {
	file_finevision_compute_v1_model_export_proto_rawDescOnce.Do(func() {
		file_finevision_compute_v1_model_export_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_finevision_compute_v1_model_export_proto_rawDesc), len(file_finevision_compute_v1_model_export_proto_rawDesc)))
	})
	return file_finevision_compute_v1_model_export_proto_rawDescData
}

var file_finevision_compute_v1_model_export_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_finevision_compute_v1_model_export_proto_goTypes = []any{
	(*ExportHeadRequest)(nil),  // 0: finevision.compute.v1.ExportHeadRequest
	(*ArtifactDescriptor)(nil), // 1: finevision.compute.v1.ArtifactDescriptor
	(*structpb.Struct)(nil),    // 2: google.protobuf.Struct
}
var file_finevision_compute_v1_model_export_proto_depIdxs = []int32{
	1, // 0: finevision.compute.v1.ExportHeadRequest.source_bundle:type_name -> finevision.compute.v1.ArtifactDescriptor
	0, // 1: finevision.compute.v1.ModelExport.ExportHead:input_type -> finevision.compute.v1.ExportHeadRequest
	2, // 2: finevision.compute.v1.ModelExport.ExportHead:output_type -> google.protobuf.Struct
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_finevision_compute_v1_model_export_proto_init() }
func file_finevision_compute_v1_model_export_proto_init() {
	if File_finevision_compute_v1_model_export_proto != nil {
		return
	}
	file_finevision_compute_v1_artifact_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_finevision_compute_v1_model_export_proto_rawDesc), len(file_finevision_compute_v1_model_export_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_finevision_compute_v1_model_export_proto_goTypes,
		DependencyIndexes: file_finevision_compute_v1_model_export_proto_depIdxs,
		MessageInfos:      file_finevision_compute_v1_model_export_proto_msgTypes,
	}.Build()
	File_finevision_compute_v1_model_export_proto = out.File
	file_finevision_compute_v1_model_export_proto_goTypes = nil
	file_finevision_compute_v1_model_export_proto_depIdxs = nil
}
