// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: finevision/compute/v1/training_lifecycle.proto

package computev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ClaimRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	JobId              string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	DispatchGeneration int64                  `protobuf:"varint,2,opt,name=dispatch_generation,json=dispatchGeneration,proto3" json:"dispatch_generation,omitempty"`
	WorkerId           string                 `protobuf:"bytes,3,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	RequestId          string                 `protobuf:"bytes,4,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ClaimRequest) Reset() {
	*x = ClaimRequest{}
	mi := &file_finevision_compute_v1_training_lifecycle_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClaimRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimRequest) ProtoMessage() {}

func (x *ClaimRequest) ProtoReflect() protoreflect.Message {
	mi := &file_finevision_compute_v1_training_lifecycle_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimRequest.ProtoReflect.Descriptor instead.
func (*ClaimRequest) Descriptor() ([]byte, []int) {
	return file_finevision_compute_v1_training_lifecycle_proto_rawDescGZIP(), []int{0}
}

func (x *ClaimRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *ClaimRequest) GetDispatchGeneration() int64 {
	if x != nil {
		return x.DispatchGeneration
	}
	return 0
}

func (x *ClaimRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *ClaimRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type ClaimResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Disposition    string                 `protobuf:"bytes,1,opt,name=disposition,proto3" json:"disposition,omitempty"`
	JobId          string                 `protobuf:"bytes,2,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	TrainingRunId  string                 `protobuf:"bytes,3,opt,name=training_run_id,json=trainingRunId,proto3" json:"training_run_id,omitempty"`
	AttemptId      string                 `protobuf:"bytes,4,opt,name=attempt_id,json=attemptId,proto3" json:"attempt_id,omitempty"`
	ExecutionEpoch int64                  `protobuf:"varint,5,opt,name=execution_epoch,json=executionEpoch,proto3" json:"execution_epoch,omitempty"`
	LeaseExpiresAt *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=lease_expires_at,json=leaseExpiresAt,proto3" json:"lease_expires_at,omitempty"`
	Payload        *structpb.Struct       `protobuf:"bytes,7,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ClaimResponse) Reset() {
	*x = ClaimResponse{}
	mi := &file_finevision_compute_v1_training_lifecycle_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClaimResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimResponse) ProtoMessage() {}

func (x *ClaimResponse) ProtoReflect() protoreflect.Message {
	mi := &file_finevision_compute_v1_training_lifecycle_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimResponse.ProtoReflect.Descriptor instead.
func (*ClaimResponse) Descriptor() ([]byte, []int) {
	return file_finevision_compute_v1_training_lifecycle_proto_rawDescGZIP(), []int{1}
}

func (x *ClaimResponse) GetDisposition() string {
	if x != nil {
		return x.Disposition
	}
	return ""
}

func (x *ClaimResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *ClaimResponse) GetTrainingRunId() string {
	if x != nil {
		return x.TrainingRunId
	}
	return ""
}

func (x *ClaimResponse) GetAttemptId() string {
	if x != nil {
		return x.AttemptId
	}
	return ""
}

func (x *ClaimResponse) GetExecutionEpoch() int64 {
	if x != nil {
		return x.ExecutionEpoch
	}
	return 0
}

func (x *ClaimResponse) GetLeaseExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LeaseExpiresAt
	}
	return nil
}

func (x *ClaimResponse) GetPayload() *structpb.Struct {
	if x != nil {
		return x.Payload
	}
	return nil
}

type HeartbeatRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	JobId          string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	AttemptId      string                 `protobuf:"bytes,2,opt,name=attempt_id,json=attemptId,proto3" json:"attempt_id,omitempty"`
	ExecutionEpoch int64                  `protobuf:"varint,3,opt,name=execution_epoch,json=executionEpoch,proto3" json:"execution_epoch,omitempty"`
	RequestId      string                 `protobuf:"bytes,4,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_finevision_compute_v1_training_lifecycle_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_finevision_compute_v1_training_lifecycle_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_finevision_compute_v1_training_lifecycle_proto_rawDescGZIP(), []int{2}
}

func (x *HeartbeatRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *HeartbeatRequest) GetAttemptId() string {
	if x != nil {
		return x.AttemptId
	}
	return ""
}

func (x *HeartbeatRequest) GetExecutionEpoch() int64 {
	if x != nil {
		return x.ExecutionEpoch
	}
	return 0
}

func (x *HeartbeatRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type HeartbeatResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Directive      string                 `protobuf:"bytes,1,opt,name=directive,proto3" json:"directive,omitempty"`
	LeaseExpiresAt *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=lease_expires_at,json=leaseExpiresAt,proto3" json:"lease_expires_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_finevision_compute_v1_training_lifecycle_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_finevision_compute_v1_training_lifecycle_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_finevision_compute_v1_training_lifecycle_proto_rawDescGZIP(), []int{3}
}

func (x *HeartbeatResponse) GetDirective() string {
	if x != nil {
		return x.Directive
	}
	return ""
}

func (x *HeartbeatResponse) GetLeaseExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LeaseExpiresAt
	}
	return nil
}

type ProgressRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	JobId          string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	AttemptId      string                 `protobuf:"bytes,2,opt,name=attempt_id,json=attemptId,proto3" json:"attempt_id,omitempty"`
	ExecutionEpoch int64                  `protobuf:"varint,3,opt,name=execution_epoch,json=executionEpoch,proto3" json:"execution_epoch,omitempty"`
	Progress       *structpb.Struct       `protobuf:"bytes,4,opt,name=progress,proto3" json:"progress,omitempty"`
	RequestId      string                 `protobuf:"bytes,5,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ProgressRequest) Reset() {
	*x = ProgressRequest{}
	mi := &file_finevision_compute_v1_training_lifecycle_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProgressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProgressRequest) ProtoMessage() {}

func (x *ProgressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_finevision_compute_v1_training_lifecycle_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProgressRequest.ProtoReflect.Descriptor instead.
func (*ProgressRequest) Descriptor() ([]byte, []int) {
	return file_finevision_compute_v1_training_lifecycle_proto_rawDescGZIP(), []int{4}
}

func (x *ProgressRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *ProgressRequest) GetAttemptId() string {
	if x != nil {
		return x.AttemptId
	}
	return ""
}

func (x *ProgressRequest) GetExecutionEpoch() int64 {
	if x != nil {
		return x.ExecutionEpoch
	}
	return 0
}

func (x *ProgressRequest) GetProgress() *structpb.Struct {
	if x != nil {
		return x.Progress
	}
	return nil
}

func (x *ProgressRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type ProgressResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProgressResponse) Reset() {
	*x = ProgressResponse{}
	mi := &file_finevision_compute_v1_training_lifecycle_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProgressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProgressResponse) ProtoMessage() {}

func (x *ProgressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_finevision_compute_v1_training_lifecycle_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProgressResponse.ProtoReflect.Descriptor instead.
func (*ProgressResponse) Descriptor() ([]byte, []int) {
	return file_finevision_compute_v1_training_lifecycle_proto_rawDescGZIP(), []int{5}
}

type CompleteRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	JobId          string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	AttemptId      string                 `protobuf:"bytes,2,opt,name=attempt_id,json=attemptId,proto3" json:"attempt_id,omitempty"`
	ExecutionEpoch int64                  `protobuf:"varint,3,opt,name=execution_epoch,json=executionEpoch,proto3" json:"execution_epoch,omitempty"`
	CompletionKey  string                 `protobuf:"bytes,4,opt,name=completion_key,json=completionKey,proto3" json:"completion_key,omitempty"`
	ResultDigest   string                 `protobuf:"bytes,5,opt,name=result_digest,json=resultDigest,proto3" json:"result_digest,omitempty"`
	Artifacts      []*ArtifactDescriptor  `protobuf:"bytes,6,rep,name=artifacts,proto3" json:"artifacts,omitempty"`
	Metrics        *structpb.Struct       `protobuf:"bytes,7,opt,name=metrics,proto3" json:"metrics,omitempty"`
	RequestId      string                 `protobuf:"bytes,8,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CompleteRequest) Reset() {
	*x = CompleteRequest{}
	mi := &file_finevision_compute_v1_training_lifecycle_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteRequest) ProtoMessage() {}

func (x *CompleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_finevision_compute_v1_training_lifecycle_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteRequest.ProtoReflect.Descriptor instead.
func (*CompleteRequest) Descriptor() ([]byte, []int) {
	return file_finevision_compute_v1_training_lifecycle_proto_rawDescGZIP(), []int{6}
}

func (x *CompleteRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *CompleteRequest) GetAttemptId() string {
	if x != nil {
		return x.AttemptId
	}
	return ""
}

func (x *CompleteRequest) GetExecutionEpoch() int64 {
	if x != nil {
		return x.ExecutionEpoch
	}
	return 0
}

func (x *CompleteRequest) GetCompletionKey() string {
	if x != nil {
		return x.CompletionKey
	}
	return ""
}

func (x *CompleteRequest) GetResultDigest() string {
	if x != nil {
		return x.ResultDigest
	}
	return ""
}

func (x *CompleteRequest) GetArtifacts() []*ArtifactDescriptor {
	if x != nil {
		return x.Artifacts
	}
	return nil
}

func (x *CompleteRequest) GetMetrics() *structpb.Struct {
	if x != nil {
		return x.Metrics
	}
	return nil
}

func (x *CompleteRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type CompleteResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	JobId          string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	TrainingRunId  string                 `protobuf:"bytes,2,opt,name=training_run_id,json=trainingRunId,proto3" json:"training_run_id,omitempty"`
	ModelVersionId string                 `protobuf:"bytes,3,opt,name=model_version_id,json=modelVersionId,proto3" json:"model_version_id,omitempty"`
	Metrics        *structpb.Struct       `protobuf:"bytes,4,opt,name=metrics,proto3" json:"metrics,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CompleteResponse) Reset() {
	*x = CompleteResponse{}
	mi := &file_finevision_compute_v1_training_lifecycle_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteResponse) ProtoMessage() {}

func (x *CompleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_finevision_compute_v1_training_lifecycle_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteResponse.ProtoReflect.Descriptor instead.
func (*CompleteResponse) Descriptor() ([]byte, []int) {
	return file_finevision_compute_v1_training_lifecycle_proto_rawDescGZIP(), []int{7}
}

func (x *CompleteResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *CompleteResponse) GetTrainingRunId() string {
	if x != nil {
		return x.TrainingRunId
	}
	return ""
}

func (x *CompleteResponse) GetModelVersionId() string {
	if x != nil {
		return x.ModelVersionId
	}
	return ""
}

func (x *CompleteResponse) GetMetrics() *structpb.Struct {
	if x != nil {
		return x.Metrics
	}
	return nil
}

type FailRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	JobId          string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	AttemptId      string                 `protobuf:"bytes,2,opt,name=attempt_id,json=attemptId,proto3" json:"attempt_id,omitempty"`
	ExecutionEpoch int64                  `protobuf:"varint,3,opt,name=execution_epoch,json=executionEpoch,proto3" json:"execution_epoch,omitempty"`
	Retryable      bool                   `protobuf:"varint,4,opt,name=retryable,proto3" json:"retryable,omitempty"`
	ErrorCode      string                 `protobuf:"bytes,5,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ErrorMessage   string                 `protobuf:"bytes,6,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	RequestId      string                 `protobuf:"bytes,7,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *FailRequest) Reset() {
	*x = FailRequest{}
	mi := &file_finevision_compute_v1_training_lifecycle_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FailRequest) ProtoMessage() {}

func (x *FailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_finevision_compute_v1_training_lifecycle_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FailRequest.ProtoReflect.Descriptor instead.
func (*FailRequest) Descriptor() ([]byte, []int) {
	return file_finevision_compute_v1_training_lifecycle_proto_rawDescGZIP(), []int{8}
}

func (x *FailRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *FailRequest) GetAttemptId() string {
	if x != nil {
		return x.AttemptId
	}
	return ""
}

func (x *FailRequest) GetExecutionEpoch() int64 {
	if x != nil {
		return x.ExecutionEpoch
	}
	return 0
}

func (x *FailRequest) GetRetryable() bool {
	if x != nil {
		return x.Retryable
	}
	return false
}

func (x *FailRequest) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *FailRequest) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *FailRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type FailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FailResponse) Reset() {
	*x = FailResponse{}
	mi := &file_finevision_compute_v1_training_lifecycle_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FailResponse) ProtoMessage() {}

func (x *FailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_finevision_compute_v1_training_lifecycle_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FailResponse.ProtoReflect.Descriptor instead.
func (*FailResponse) Descriptor() ([]byte, []int) {
	return file_finevision_compute_v1_training_lifecycle_proto_rawDescGZIP(), []int{9}
}

var File_finevision_compute_v1_training_lifecycle_proto protoreflect.FileDescriptor

const file_finevision_compute_v1_training_lifecycle_proto_rawDesc = "" +
	"\n" +
	".finevision/compute/v1/training_lifecycle.proto\x12\x15finevision.compute.v1\x1a$finevision/compute/v1/artifact.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x92\x01\n" +
	"\fClaimRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12/\n" +
	"\x13dispatch_generation\x18\x02 \x01(\x03R\x12dispatchGeneration\x12\x1b\n" +
	"\tworker_id\x18\x03 \x01(\tR\bworkerId\x12\x1d\n" +
	"\n" +
	"request_id\x18\x04 \x01(\tR\trequestId\"\xb1\x02\n" +
	"\rClaimResponse\x12 \n" +
	"\vdisposition\x18\x01 \x01(\tR\vdisposition\x12\x15\n" +
	"\x06job_id\x18\x02 \x01(\tR\x05jobId\x12&\n" +
	"\x0ftraining_run_id\x18\x03 \x01(\tR\rtrainingRunId\x12\x1d\n" +
	"\n" +
	"attempt_id\x18\x04 \x01(\tR\tattemptId\x12'\n" +
	"\x0fexecution_epoch\x18\x05 \x01(\x03R\x0eexecutionEpoch\x12D\n" +
	"\x10lease_expires_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\x0eleaseExpiresAt\x121\n" +
	"\apayload\x18\a \x01(\v2\x17.google.protobuf.StructR\apayload\"\x90\x01\n" +
	"\x10HeartbeatRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x1d\n" +
	"\n" +
	"attempt_id\x18\x02 \x01(\tR\tattemptId\x12'\n" +
	"\x0fexecution_epoch\x18\x03 \x01(\x03R\x0eexecutionEpoch\x12\x1d\n" +
	"\n" +
	"request_id\x18\x04 \x01(\tR\trequestId\"w\n" +
	"\x11HeartbeatResponse\x12\x1c\n" +
	"\tdirective\x18\x01 \x01(\tR\tdirective\x12D\n" +
	"\x10lease_expires_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x0eleaseExpiresAt\"\xc4\x01\n" +
	"\x0fProgressRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x1d\n" +
	"\n" +
	"attempt_id\x18\x02 \x01(\tR\tattemptId\x12'\n" +
	"\x0fexecution_epoch\x18\x03 \x01(\x03R\x0eexecutionEpoch\x123\n" +
	"\bprogress\x18\x04 \x01(\v2\x17.google.protobuf.StructR\bprogress\x12\x1d\n" +
	"\n" +
	"request_id\x18\x05 \x01(\tR\trequestId\"\x12\n" +
	"\x10ProgressResponse\"\xd7\x02\n" +
	"\x0fCompleteRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x1d\n" +
	"\n" +
	"attempt_id\x18\x02 \x01(\tR\tattemptId\x12'\n" +
	"\x0fexecution_epoch\x18\x03 \x01(\x03R\x0eexecutionEpoch\x12%\n" +
	"\x0ecompletion_key\x18\x04 \x01(\tR\rcompletionKey\x12#\n" +
	"\rresult_digest\x18\x05 \x01(\tR\fresultDigest\x12G\n" +
	"\tartifacts\x18\x06 \x03(\v2).finevision.compute.v1.ArtifactDescriptorR\tartifacts\x121\n" +
	"\ametrics\x18\a \x01(\v2\x17.google.protobuf.StructR\ametrics\x12\x1d\n" +
	"\n" +
	"request_id\x18\b \x01(\tR\trequestId\"\xae\x01\n" +
	"\x10CompleteResponse\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12&\n" +
	"\x0ftraining_run_id\x18\x02 \x01(\tR\rtrainingRunId\x12(\n" +
	"\x10model_version_id\x18\x03 \x01(\tR\x0emodelVersionId\x121\n" +
	"\ametrics\x18\x04 \x01(\v2\x17.google.protobuf.StructR\ametrics\"\xed\x01\n" +
	"\vFailRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x1d\n" +
	"\n" +
	"attempt_id\x18\x02 \x01(\tR\tattemptId\x12'\n" +
	"\x0fexecution_epoch\x18\x03 \x01(\x03R\x0eexecutionEpoch\x12\x1c\n" +
	"\tretryable\x18\x04 \x01(\bR\tretryable\x12\x1d\n" +
	"\n" +
	"error_code\x18\x05 \x01(\tR\terrorCode\x12#\n" +
	"\rerror_message\x18\x06 \x01(\tR\ferrorMessage\x12\x1d\n" +
	"\n" +
	"request_id\x18\a \x01(\tR\trequestId\"\x0e\n" +
	"\fFailResponse2\xd8\x03\n" +
	"\x11TrainingLifecycle\x12R\n" +
	"\x05Claim\x12#.finevision.compute.v1.ClaimRequest\x1a$.finevision.compute.v1.ClaimResponse\x12^\n" +
	"\tHeartbeat\x12'.finevision.compute.v1.HeartbeatRequest\x1a(.finevision.compute.v1.HeartbeatResponse\x12a\n" +
	"\x0eReportProgress\x12&.finevision.compute.v1.ProgressRequest\x1a'.finevision.compute.v1.ProgressResponse\x12[\n" +
	"\bComplete\x12&.finevision.compute.v1.CompleteRequest\x1a'.finevision.compute.v1.CompleteResponse\x12O\n" +
	"\x04Fail\x12\".finevision.compute.v1.FailRequest\x1a#.finevision.compute.v1.FailResponseBXZVgithub.com/tianyuqic1/FGVCplateformPublic/go/api/proto/finevision/compute/v1;computev1b\x06proto3"

var (
	file_finevision_compute_v1_training_lifecycle_proto_rawDescOnce sync.Once
	file_finevision_compute_v1_training_lifecycle_proto_rawDescData []byte
)

func file_finevision_compute_v1_training_lifecycle_proto_rawDescGZIP() []byte {
	file_finevision_compute_v1_training_lifecycle_proto_rawDescOnce.Do(func() {
		file_finevision_compute_v1_training_lifecycle_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_finevision_compute_v1_training_lifecycle_proto_rawDesc), len(file_finevision_compute_v1_training_lifecycle_proto_rawDesc)))
	})
	return file_finevision_compute_v1_training_lifecycle_proto_rawDescData
}

var file_finevision_compute_v1_training_lifecycle_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_finevision_compute_v1_training_lifecycle_proto_goTypes = []any{
	(*ClaimRequest)(nil),          // 0: finevision.compute.v1.ClaimRequest
	(*ClaimResponse)(nil),         // 1: finevision.compute.v1.ClaimResponse
	(*HeartbeatRequest)(nil),      // 2: finevision.compute.v1.HeartbeatRequest
	(*HeartbeatResponse)(nil),     // 3: finevision.compute.v1.HeartbeatResponse
	(*ProgressRequest)(nil),       // 4: finevision.compute.v1.ProgressRequest
	(*ProgressResponse)(nil),      // 5: finevision.compute.v1.ProgressResponse
	(*CompleteRequest)(nil),       // 6: finevision.compute.v1.CompleteRequest
	(*CompleteResponse)(nil),      // 7: finevision.compute.v1.CompleteResponse
	(*FailRequest)(nil),           // 8: finevision.compute.v1.FailRequest
	(*FailResponse)(nil),          // 9: finevision.compute.v1.FailResponse
	(*timestamppb.Timestamp)(nil), // 10: google.protobuf.Timestamp
	(*structpb.Struct)(nil),       // 11: google.protobuf.Struct
	(*ArtifactDescriptor)(nil),    // 12: finevision.compute.v1.ArtifactDescriptor
}
var file_finevision_compute_v1_training_lifecycle_proto_depIdxs = []int32{
	10, // 0: finevision.compute.v1.ClaimResponse.lease_expires_at:type_name -> google.protobuf.Timestamp
	11, // 1: finevision.compute.v1.ClaimResponse.payload:type_name -> google.protobuf.Struct
	10, // 2: finevision.compute.v1.HeartbeatResponse.lease_expires_at:type_name -> google.protobuf.Timestamp
	11, // 3: finevision.compute.v1.ProgressRequest.progress:type_name -> google.protobuf.Struct
	12, // 4: finevision.compute.v1.CompleteRequest.artifacts:type_name -> finevision.compute.v1.ArtifactDescriptor
	11, // 5: finevision.compute.v1.CompleteRequest.metrics:type_name -> google.protobuf.Struct
	11, // 6: finevision.compute.v1.CompleteResponse.metrics:type_name -> google.protobuf.Struct
	0,  // 7: finevision.compute.v1.TrainingLifecycle.Claim:input_type -> finevision.compute.v1.ClaimRequest
	2,  // 8: finevision.compute.v1.TrainingLifecycle.Heartbeat:input_type -> finevision.compute.v1.HeartbeatRequest
	4,  // 9: finevision.compute.v1.TrainingLifecycle.ReportProgress:input_type -> finevision.compute.v1.ProgressRequest
	6,  // 10: finevision.compute.v1.TrainingLifecycle.Complete:input_type -> finevision.compute.v1.CompleteRequest
	8,  // 11: finevision.compute.v1.TrainingLifecycle.Fail:input_type -> finevision.compute.v1.FailRequest
	1,  // 12: finevision.compute.v1.TrainingLifecycle.Claim:output_type -> finevision.compute.v1.ClaimResponse
	3,  // 13: finevision.compute.v1.TrainingLifecycle.Heartbeat:output_type -> finevision.compute.v1.HeartbeatResponse
	5,  // 14: finevision.compute.v1.TrainingLifecycle.ReportProgress:output_type -> finevision.compute.v1.ProgressResponse
	7,  // 15: finevision.compute.v1.TrainingLifecycle.Complete:output_type -> finevision.compute.v1.CompleteResponse
	9,  // 16: finevision.compute.v1.TrainingLifecycle.Fail:output_type -> finevision.compute.v1.FailResponse
	12, // [12:17] is the sub-list for method output_type
	7,  // [7:12] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_finevision_compute_v1_training_lifecycle_proto_init() }
func file_finevision_compute_v1_training_lifecycle_proto_init() {
	if File_finevision_compute_v1_training_lifecycle_proto != nil {
		return
	}
	file_finevision_compute_v1_artifact_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_finevision_compute_v1_training_lifecycle_proto_rawDesc), len(file_finevision_compute_v1_training_lifecycle_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_finevision_compute_v1_training_lifecycle_proto_goTypes,
		DependencyIndexes: file_finevision_compute_v1_training_lifecycle_proto_depIdxs,
		MessageInfos:      file_finevision_compute_v1_training_lifecycle_proto_msgTypes,
	}.Build()
	File_finevision_compute_v1_training_lifecycle_proto = out.File
	file_finevision_compute_v1_training_lifecycle_proto_goTypes = nil
	file_finevision_compute_v1_training_lifecycle_proto_depIdxs = nil
}
