// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.35.1
// source: finevision/compute/v1/training_lifecycle.proto

package computev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TrainingLifecycle_Claim_FullMethodName          = "/finevision.compute.v1.TrainingLifecycle/Claim"
	TrainingLifecycle_Heartbeat_FullMethodName      = "/finevision.compute.v1.TrainingLifecycle/Heartbeat"
	TrainingLifecycle_ReportProgress_FullMethodName = "/finevision.compute.v1.TrainingLifecycle/ReportProgress"
	TrainingLifecycle_Complete_FullMethodName       = "/finevision.compute.v1.TrainingLifecycle/Complete"
	TrainingLifecycle_Fail_FullMethodName           = "/finevision.compute.v1.TrainingLifecycle/Fail"
)

// TrainingLifecycleClient is the client API for TrainingLifecycle service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TrainingLifecycleClient interface {
	Claim(ctx context.Context, in *ClaimRequest, opts ...grpc.CallOption) (*ClaimResponse, error)
	Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error)
	ReportProgress(ctx context.Context, in *ProgressRequest, opts ...grpc.CallOption) (*ProgressResponse, error)
	Complete(ctx context.Context, in *CompleteRequest, opts ...grpc.CallOption) (*CompleteResponse, error)
	Fail(ctx context.Context, in *FailRequest, opts ...grpc.CallOption) (*FailResponse, error)
}

type trainingLifecycleClient struct {
	cc grpc.ClientConnInterface
}

func NewTrainingLifecycleClient(cc grpc.ClientConnInterface) TrainingLifecycleClient {
	return &trainingLifecycleClient{cc}
}

func (c *trainingLifecycleClient) Claim(ctx context.Context, in *ClaimRequest, opts ...grpc.CallOption) (*ClaimResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClaimResponse)
	err := c.cc.Invoke(ctx, TrainingLifecycle_Claim_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trainingLifecycleClient) Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HeartbeatResponse)
	err := c.cc.Invoke(ctx, TrainingLifecycle_Heartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trainingLifecycleClient) ReportProgress(ctx context.Context, in *ProgressRequest, opts ...grpc.CallOption) (*ProgressResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProgressResponse)
	err := c.cc.Invoke(ctx, TrainingLifecycle_ReportProgress_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trainingLifecycleClient) Complete(ctx context.Context, in *CompleteRequest, opts ...grpc.CallOption) (*CompleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CompleteResponse)
	err := c.cc.Invoke(ctx, TrainingLifecycle_Complete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trainingLifecycleClient) Fail(ctx context.Context, in *FailRequest, opts ...grpc.CallOption) (*FailResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FailResponse)
	err := c.cc.Invoke(ctx, TrainingLifecycle_Fail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TrainingLifecycleServer is the server API for TrainingLifecycle service.
// All implementations must embed UnimplementedTrainingLifecycleServer
// for forward compatibility.
type TrainingLifecycleServer interface {
	Claim(context.Context, *ClaimRequest) (*ClaimResponse, error)
	Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error)
	ReportProgress(context.Context, *ProgressRequest) (*ProgressResponse, error)
	Complete(context.Context, *CompleteRequest) (*CompleteResponse, error)
	Fail(context.Context, *FailRequest) (*FailResponse, error)
	mustEmbedUnimplementedTrainingLifecycleServer()
}

// UnimplementedTrainingLifecycleServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTrainingLifecycleServer struct{}

func (UnimplementedTrainingLifecycleServer) Claim(context.Context, *ClaimRequest) (*ClaimResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Claim not implemented")
}
func (UnimplementedTrainingLifecycleServer) Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedTrainingLifecycleServer) ReportProgress(context.Context, *ProgressRequest) (*ProgressResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportProgress not implemented")
}
func (UnimplementedTrainingLifecycleServer) Complete(context.Context, *CompleteRequest) (*CompleteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Complete not implemented")
}
func (UnimplementedTrainingLifecycleServer) Fail(context.Context, *FailRequest) (*FailResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Fail not implemented")
}
func (UnimplementedTrainingLifecycleServer) mustEmbedUnimplementedTrainingLifecycleServer() {}
func (UnimplementedTrainingLifecycleServer) testEmbeddedByValue()                           {}

// UnsafeTrainingLifecycleServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TrainingLifecycleServer will
// result in compilation errors.
type UnsafeTrainingLifecycleServer interface {
	mustEmbedUnimplementedTrainingLifecycleServer()
}

func RegisterTrainingLifecycleServer(s grpc.ServiceRegistrar, srv TrainingLifecycleServer) {
	// If the following call panics, it indicates UnimplementedTrainingLifecycleServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TrainingLifecycle_ServiceDesc, srv)
}

func _TrainingLifecycle_Claim_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClaimRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrainingLifecycleServer).Claim(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TrainingLifecycle_Claim_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrainingLifecycleServer).Claim(ctx, req.(*ClaimRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TrainingLifecycle_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrainingLifecycleServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TrainingLifecycle_Heartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrainingLifecycleServer).Heartbeat(ctx, req.(*HeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TrainingLifecycle_ReportProgress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProgressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrainingLifecycleServer).ReportProgress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TrainingLifecycle_ReportProgress_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrainingLifecycleServer).ReportProgress(ctx, req.(*ProgressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TrainingLifecycle_Complete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrainingLifecycleServer).Complete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TrainingLifecycle_Complete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrainingLifecycleServer).Complete(ctx, req.(*CompleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TrainingLifecycle_Fail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrainingLifecycleServer).Fail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TrainingLifecycle_Fail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrainingLifecycleServer).Fail(ctx, req.(*FailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TrainingLifecycle_ServiceDesc is the grpc.ServiceDesc for TrainingLifecycle service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TrainingLifecycle_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "finevision.compute.v1.TrainingLifecycle",
	HandlerType: (*TrainingLifecycleServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Claim",
			Handler:    _TrainingLifecycle_Claim_Handler,
		},
		{
			MethodName: "Heartbeat",
			Handler:    _TrainingLifecycle_Heartbeat_Handler,
		},
		{
			MethodName: "ReportProgress",
			Handler:    _TrainingLifecycle_ReportProgress_Handler,
		},
		{
			MethodName: "Complete",
			Handler:    _TrainingLifecycle_Complete_Handler,
		},
		{
			MethodName: "Fail",
			Handler:    _TrainingLifecycle_Fail_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "finevision/compute/v1/training_lifecycle.proto",
}
