# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: finevision/compute/v1/artifact.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'finevision/compute/v1/artifact.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$finevision/compute/v1/artifact.proto\x12\x15\x66inevision.compute.v1\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x9f\x03\n\x12\x41rtifactDescriptor\x12\x13\n\x0b\x61rtifact_id\x18\x01 \x01(\t\x12\x15\n\rartifact_type\x18\x02 \x01(\t\x12\x0b\n\x03uri\x18\x03 \x01(\t\x12\x0e\n\x06sha256\x18\x04 \x01(\t\x12\x12\n\nsize_bytes\x18\x05 \x01(\x03\x12\x14\n\x0c\x63ontent_type\x18\x06 \x01(\t\x12\x17\n\x0fstorage_version\x18\x07 \x01(\t\x12\x10\n\x08producer\x18\x08 \x01(\t\x12\x1a\n\x12\x64\x61taset_version_id\x18\t \x01(\t\x12\x17\n\x0ftraining_run_id\x18\n \x01(\t\x12\x12\n\nattempt_id\x18\x0b \x01(\t\x12\x16\n\x0eschema_version\x18\x0c \x01(\x05\x12.\n\ncreated_at\x18\r \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12/\n\x0bverified_at\x18\x0e \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12)\n\x08metadata\x18\x0f \x01(\x0b\x32\x17.google.protobuf.StructBXZVgithub.com/tianyuqic1/FGVCplateformPublic/go/api/proto/finevision/compute/v1;computev1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'finevision.compute.v1.artifact_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZVgithub.com/tianyuqic1/FGVCplateformPublic/go/api/proto/finevision/compute/v1;computev1'
  _globals['_ARTIFACTDESCRIPTOR']._serialized_start=127
  _globals['_ARTIFACTDESCRIPTOR']._serialized_end=542
# @@protoc_insertion_point(module_scope)
