# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from finevision.compute.v1 import inference_runtime_pb2 as finevision_dot_compute_dot_v1_dot_inference__runtime__pb2

GRPC_GENERATED_VERSION = '1.83.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in finevision/compute/v1/inference_runtime_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class InferenceRuntimeStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Predict = channel.unary_unary(
                '/finevision.compute.v1.InferenceRuntime/Predict',
                request_serializer=finevision_dot_compute_dot_v1_dot_inference__runtime__pb2.PredictRequest.SerializeToString,
                response_deserializer=finevision_dot_compute_dot_v1_dot_inference__runtime__pb2.Prediction.FromString,
                _registered_method=True)
        self.EvictCache = channel.unary_unary(
                '/finevision.compute.v1.InferenceRuntime/EvictCache',
                request_serializer=finevision_dot_compute_dot_v1_dot_inference__runtime__pb2.EvictCacheRequest.SerializeToString,
                response_deserializer=finevision_dot_compute_dot_v1_dot_inference__runtime__pb2.EvictCacheResponse.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/finevision.compute.v1.InferenceRuntime/Health',
                request_serializer=finevision_dot_compute_dot_v1_dot_inference__runtime__pb2.HealthRequest.SerializeToString,
                response_deserializer=finevision_dot_compute_dot_v1_dot_inference__runtime__pb2.HealthResponse.FromString,
                _registered_method=True)


class InferenceRuntimeServicer:
    """Missing associated documentation comment in .proto file."""

    def Predict(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EvictCache(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_InferenceRuntimeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Predict': grpc.unary_unary_rpc_method_handler(
                    servicer.Predict,
                    request_deserializer=finevision_dot_compute_dot_v1_dot_inference__runtime__pb2.PredictRequest.FromString,
                    response_serializer=finevision_dot_compute_dot_v1_dot_inference__runtime__pb2.Prediction.SerializeToString,
            ),
            'EvictCache': grpc.unary_unary_rpc_method_handler(
                    servicer.EvictCache,
                    request_deserializer=finevision_dot_compute_dot_v1_dot_inference__runtime__pb2.EvictCacheRequest.FromString,
                    response_serializer=finevision_dot_compute_dot_v1_dot_inference__runtime__pb2.EvictCacheResponse.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=finevision_dot_compute_dot_v1_dot_inference__runtime__pb2.HealthRequest.FromString,
                    response_serializer=finevision_dot_compute_dot_v1_dot_inference__runtime__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'finevision.compute.v1.InferenceRuntime', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('finevision.compute.v1.InferenceRuntime', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class InferenceRuntime:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Predict(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/finevision.compute.v1.InferenceRuntime/Predict',
            finevision_dot_compute_dot_v1_dot_inference__runtime__pb2.PredictRequest.SerializeToString,
            finevision_dot_compute_dot_v1_dot_inference__runtime__pb2.Prediction.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EvictCache(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/finevision.compute.v1.InferenceRuntime/EvictCache',
            finevision_dot_compute_dot_v1_dot_inference__runtime__pb2.EvictCacheRequest.SerializeToString,
            finevision_dot_compute_dot_v1_dot_inference__runtime__pb2.EvictCacheResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/finevision.compute.v1.InferenceRuntime/Health',
            finevision_dot_compute_dot_v1_dot_inference__runtime__pb2.HealthRequest.SerializeToString,
            finevision_dot_compute_dot_v1_dot_inference__runtime__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
