# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: finevision/compute/v1/inference_runtime.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'finevision/compute/v1/inference_runtime.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from finevision.compute.v1 import artifact_pb2 as finevision_dot_compute_dot_v1_dot_artifact__pb2
from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n-finevision/compute/v1/inference_runtime.proto\x12\x15\x66inevision.compute.v1\x1a$finevision/compute/v1/artifact.proto\x1a\x1cgoogle/protobuf/struct.proto\"\xce\x01\n\x0ePredictRequest\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12?\n\x0cmodel_bundle\x18\x02 \x01(\x0b\x32).finevision.compute.v1.ArtifactDescriptor\x12>\n\x0binput_image\x18\x03 \x01(\x0b\x32).finevision.compute.v1.ArtifactDescriptor\x12\'\n\x06policy\x18\x04 \x01(\x0b\x32\x17.google.protobuf.Struct\"\xc3\x01\n\nPrediction\x12\x30\n\x05top_k\x18\x01 \x03(\x0b\x32!.finevision.compute.v1.LabelScore\x12\x10\n\x08\x64\x65\x63ision\x18\x02 \x01(\t\x12\x12\n\nconfidence\x18\x03 \x01(\x01\x12\x0e\n\x06margin\x18\x04 \x01(\x01\x12\x11\n\tood_score\x18\x05 \x01(\x01\x12\x0f\n\x07reasons\x18\x06 \x03(\t\x12)\n\x08\x65vidence\x18\x07 \x01(\x0b\x32\x17.google.protobuf.Struct\"*\n\nLabelScore\x12\r\n\x05label\x18\x01 \x01(\t\x12\r\n\x05score\x18\x02 \x01(\x01\"#\n\x11\x45victCacheRequest\x12\x0e\n\x06sha256\x18\x01 \x01(\t\"%\n\x12\x45victCacheResponse\x12\x0f\n\x07\x65victed\x18\x01 \x01(\x08\"\x0f\n\rHealthRequest\" \n\x0eHealthResponse\x12\x0e\n\x06status\x18\x01 \x01(\t2\xa1\x02\n\x10InferenceRuntime\x12S\n\x07Predict\x12%.finevision.compute.v1.PredictRequest\x1a!.finevision.compute.v1.Prediction\x12\x61\n\nEvictCache\x12(.finevision.compute.v1.EvictCacheRequest\x1a).finevision.compute.v1.EvictCacheResponse\x12U\n\x06Health\x12$.finevision.compute.v1.HealthRequest\x1a%.finevision.compute.v1.HealthResponseBXZVgithub.com/tianyuqic1/FGVCplateformPublic/go/api/proto/finevision/compute/v1;computev1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'finevision.compute.v1.inference_runtime_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZVgithub.com/tianyuqic1/FGVCplateformPublic/go/api/proto/finevision/compute/v1;computev1'
  _globals['_PREDICTREQUEST']._serialized_start=141
  _globals['_PREDICTREQUEST']._serialized_end=347
  _globals['_PREDICTION']._serialized_start=350
  _globals['_PREDICTION']._serialized_end=545
  _globals['_LABELSCORE']._serialized_start=547
  _globals['_LABELSCORE']._serialized_end=589
  _globals['_EVICTCACHEREQUEST']._serialized_start=591
  _globals['_EVICTCACHEREQUEST']._serialized_end=626
  _globals['_EVICTCACHERESPONSE']._serialized_start=628
  _globals['_EVICTCACHERESPONSE']._serialized_end=665
  _globals['_HEALTHREQUEST']._serialized_start=667
  _globals['_HEALTHREQUEST']._serialized_end=682
  _globals['_HEALTHRESPONSE']._serialized_start=684
  _globals['_HEALTHRESPONSE']._serialized_end=716
  _globals['_INFERENCERUNTIME']._serialized_start=719
  _globals['_INFERENCERUNTIME']._serialized_end=1008
# @@protoc_insertion_point(module_scope)
