# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: finevision/compute/v1/model_export.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'finevision/compute/v1/model_export.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from finevision.compute.v1 import artifact_pb2 as finevision_dot_compute_dot_v1_dot_artifact__pb2
from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n(finevision/compute/v1/model_export.proto\x12\x15\x66inevision.compute.v1\x1a$finevision/compute/v1/artifact.proto\x1a\x1cgoogle/protobuf/struct.proto\"\xa4\x01\n\x11\x45xportHeadRequest\x12\x18\n\x10model_version_id\x18\x01 \x01(\t\x12\x1a\n\x12\x64\x61taset_version_id\x18\x02 \x01(\t\x12\x17\n\x0ftraining_run_id\x18\x03 \x01(\t\x12@\n\rsource_bundle\x18\x04 \x01(\x0b\x32).finevision.compute.v1.ArtifactDescriptor2^\n\x0bModelExport\x12O\n\nExportHead\x12(.finevision.compute.v1.ExportHeadRequest\x1a\x17.google.protobuf.StructBXZVgithub.com/tianyuqic1/FGVCplateformPublic/go/api/proto/finevision/compute/v1;computev1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'finevision.compute.v1.model_export_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZVgithub.com/tianyuqic1/FGVCplateformPublic/go/api/proto/finevision/compute/v1;computev1'
  _globals['_EXPORTHEADREQUEST']._serialized_start=136
  _globals['_EXPORTHEADREQUEST']._serialized_end=300
  _globals['_MODELEXPORT']._serialized_start=302
  _globals['_MODELEXPORT']._serialized_end=396
# @@protoc_insertion_point(module_scope)
