# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from finevision.compute.v1 import training_lifecycle_pb2 as finevision_dot_compute_dot_v1_dot_training__lifecycle__pb2

GRPC_GENERATED_VERSION = '1.83.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in finevision/compute/v1/training_lifecycle_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TrainingLifecycleStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Claim = channel.unary_unary(
                '/finevision.compute.v1.TrainingLifecycle/Claim',
                request_serializer=finevision_dot_compute_dot_v1_dot_training__lifecycle__pb2.ClaimRequest.SerializeToString,
                response_deserializer=finevision_dot_compute_dot_v1_dot_training__lifecycle__pb2.ClaimResponse.FromString,
                _registered_method=True)
        self.Heartbeat = channel.unary_unary(
                '/finevision.compute.v1.TrainingLifecycle/Heartbeat',
                request_serializer=finevision_dot_compute_dot_v1_dot_training__lifecycle__pb2.HeartbeatRequest.SerializeToString,
                response_deserializer=finevision_dot_compute_dot_v1_dot_training__lifecycle__pb2.HeartbeatResponse.FromString,
                _registered_method=True)
        self.ReportProgress = channel.unary_unary(
                '/finevision.compute.v1.TrainingLifecycle/ReportProgress',
                request_serializer=finevision_dot_compute_dot_v1_dot_training__lifecycle__pb2.ProgressRequest.SerializeToString,
                response_deserializer=finevision_dot_compute_dot_v1_dot_training__lifecycle__pb2.ProgressResponse.FromString,
                _registered_method=True)
        self.Complete = channel.unary_unary(
                '/finevision.compute.v1.TrainingLifecycle/Complete',
                request_serializer=finevision_dot_compute_dot_v1_dot_training__lifecycle__pb2.CompleteRequest.SerializeToString,
                response_deserializer=finevision_dot_compute_dot_v1_dot_training__lifecycle__pb2.CompleteResponse.FromString,
                _registered_method=True)
        self.Fail = channel.unary_unary(
                '/finevision.compute.v1.TrainingLifecycle/Fail',
                request_serializer=finevision_dot_compute_dot_v1_dot_training__lifecycle__pb2.FailRequest.SerializeToString,
                response_deserializer=finevision_dot_compute_dot_v1_dot_training__lifecycle__pb2.FailResponse.FromString,
                _registered_method=True)


class TrainingLifecycleServicer:
    """Missing associated documentation comment in .proto file."""

    def Claim(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Heartbeat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReportProgress(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Complete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Fail(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TrainingLifecycleServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Claim': grpc.unary_unary_rpc_method_handler(
                    servicer.Claim,
                    request_deserializer=finevision_dot_compute_dot_v1_dot_training__lifecycle__pb2.ClaimRequest.FromString,
                    response_serializer=finevision_dot_compute_dot_v1_dot_training__lifecycle__pb2.ClaimResponse.SerializeToString,
            ),
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=finevision_dot_compute_dot_v1_dot_training__lifecycle__pb2.HeartbeatRequest.FromString,
                    response_serializer=finevision_dot_compute_dot_v1_dot_training__lifecycle__pb2.HeartbeatResponse.SerializeToString,
            ),
            'ReportProgress': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportProgress,
                    request_deserializer=finevision_dot_compute_dot_v1_dot_training__lifecycle__pb2.ProgressRequest.FromString,
                    response_serializer=finevision_dot_compute_dot_v1_dot_training__lifecycle__pb2.ProgressResponse.SerializeToString,
            ),
            'Complete': grpc.unary_unary_rpc_method_handler(
                    servicer.Complete,
                    request_deserializer=finevision_dot_compute_dot_v1_dot_training__lifecycle__pb2.CompleteRequest.FromString,
                    response_serializer=finevision_dot_compute_dot_v1_dot_training__lifecycle__pb2.CompleteResponse.SerializeToString,
            ),
            'Fail': grpc.unary_unary_rpc_method_handler(
                    servicer.Fail,
                    request_deserializer=finevision_dot_compute_dot_v1_dot_training__lifecycle__pb2.FailRequest.FromString,
                    response_serializer=finevision_dot_compute_dot_v1_dot_training__lifecycle__pb2.FailResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'finevision.compute.v1.TrainingLifecycle', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('finevision.compute.v1.TrainingLifecycle', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TrainingLifecycle:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Claim(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/finevision.compute.v1.TrainingLifecycle/Claim',
            finevision_dot_compute_dot_v1_dot_training__lifecycle__pb2.ClaimRequest.SerializeToString,
            finevision_dot_compute_dot_v1_dot_training__lifecycle__pb2.ClaimResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/finevision.compute.v1.TrainingLifecycle/Heartbeat',
            finevision_dot_compute_dot_v1_dot_training__lifecycle__pb2.HeartbeatRequest.SerializeToString,
            finevision_dot_compute_dot_v1_dot_training__lifecycle__pb2.HeartbeatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReportProgress(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/finevision.compute.v1.TrainingLifecycle/ReportProgress',
            finevision_dot_compute_dot_v1_dot_training__lifecycle__pb2.ProgressRequest.SerializeToString,
            finevision_dot_compute_dot_v1_dot_training__lifecycle__pb2.ProgressResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Complete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/finevision.compute.v1.TrainingLifecycle/Complete',
            finevision_dot_compute_dot_v1_dot_training__lifecycle__pb2.CompleteRequest.SerializeToString,
            finevision_dot_compute_dot_v1_dot_training__lifecycle__pb2.CompleteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Fail(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/finevision.compute.v1.TrainingLifecycle/Fail',
            finevision_dot_compute_dot_v1_dot_training__lifecycle__pb2.FailRequest.SerializeToString,
            finevision_dot_compute_dot_v1_dot_training__lifecycle__pb2.FailResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
