services:
  api:
    environment:
      FINEVISION_DINOV3_DEVICE: cuda
    devices:
      - nvidia.com/gpu=all

  ml-worker:
    environment:
      FINEVISION_DINOV3_DEVICE: cuda
      FINEVISION_LINEAR_HEAD_DEVICE: cuda
    devices:
      - nvidia.com/gpu=all
