// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package openapi

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"time"

	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for ArtifactDescriptorSchemaVersion.
const (
	N1 ArtifactDescriptorSchemaVersion = 1
)

// Valid indicates whether the value is a known member of the ArtifactDescriptorSchemaVersion enum.
func (e ArtifactDescriptorSchemaVersion) Valid() bool {
	switch e {
	case N1:
		return true
	default:
		return false
	}
}

// Defines values for ClaimResultDisposition.
const (
	Claimed  ClaimResultDisposition = "claimed"
	Obsolete ClaimResultDisposition = "obsolete"
	Terminal ClaimResultDisposition = "terminal"
)

// Valid indicates whether the value is a known member of the ClaimResultDisposition enum.
func (e ClaimResultDisposition) Valid() bool {
	switch e {
	case Claimed:
		return true
	case Obsolete:
		return true
	case Terminal:
		return true
	default:
		return false
	}
}

// Defines values for CreateTrainingRunExtractor.
const (
	ColorStats CreateTrainingRunExtractor = "color_stats"
	Dinov3Vitb CreateTrainingRunExtractor = "dinov3_vitb"
	Dinov3Vitl CreateTrainingRunExtractor = "dinov3_vitl"
	Dinov3Vits CreateTrainingRunExtractor = "dinov3_vits"
)

// Valid indicates whether the value is a known member of the CreateTrainingRunExtractor enum.
func (e CreateTrainingRunExtractor) Valid() bool {
	switch e {
	case ColorStats:
		return true
	case Dinov3Vitb:
		return true
	case Dinov3Vitl:
		return true
	case Dinov3Vits:
		return true
	default:
		return false
	}
}

// Defines values for CreateTrainingRunFeaturePool.
const (
	Cls   CreateTrainingRunFeaturePool = "cls"
	Model CreateTrainingRunFeaturePool = "model"
)

// Valid indicates whether the value is a known member of the CreateTrainingRunFeaturePool enum.
func (e CreateTrainingRunFeaturePool) Valid() bool {
	switch e {
	case Cls:
		return true
	case Model:
		return true
	default:
		return false
	}
}

// Defines values for HealthRuntime.
const (
	GoControlPlane HealthRuntime = "go-control-plane"
)

// Valid indicates whether the value is a known member of the HealthRuntime enum.
func (e HealthRuntime) Valid() bool {
	switch e {
	case GoControlPlane:
		return true
	default:
		return false
	}
}

// Defines values for HealthStatus.
const (
	Ok HealthStatus = "ok"
)

// Valid indicates whether the value is a known member of the HealthStatus enum.
func (e HealthStatus) Valid() bool {
	switch e {
	case Ok:
		return true
	default:
		return false
	}
}

// Defines values for HeartbeatResultDirective.
const (
	Cancel   HeartbeatResultDirective = "cancel"
	Continue HeartbeatResultDirective = "continue"
	Fenced   HeartbeatResultDirective = "fenced"
	Pause    HeartbeatResultDirective = "pause"
)

// Valid indicates whether the value is a known member of the HeartbeatResultDirective enum.
func (e HeartbeatResultDirective) Valid() bool {
	switch e {
	case Cancel:
		return true
	case Continue:
		return true
	case Fenced:
		return true
	case Pause:
		return true
	default:
		return false
	}
}

// Defines values for LLMAssistanceRequestTask.
const (
	FeedbackCuration     LLMAssistanceRequestTask = "feedback_curation"
	InferenceExplanation LLMAssistanceRequestTask = "inference_explanation"
	ReviewAssistance     LLMAssistanceRequestTask = "review_assistance"
	TrainingDiagnosis    LLMAssistanceRequestTask = "training_diagnosis"
)

// Valid indicates whether the value is a known member of the LLMAssistanceRequestTask enum.
func (e LLMAssistanceRequestTask) Valid() bool {
	switch e {
	case FeedbackCuration:
		return true
	case InferenceExplanation:
		return true
	case ReviewAssistance:
		return true
	case TrainingDiagnosis:
		return true
	default:
		return false
	}
}

// ArtifactDescriptor defines model for ArtifactDescriptor.
type ArtifactDescriptor struct {
	ArtifactId       openapi_types.UUID              `json:"artifact_id"`
	ArtifactType     string                          `json:"artifact_type"`
	AttemptId        *string                         `json:"attempt_id,omitempty"`
	ContentType      string                          `json:"content_type"`
	CreatedAt        *time.Time                      `json:"created_at,omitempty"`
	DatasetVersionId *string                         `json:"dataset_version_id,omitempty"`
	Metadata         *FreeFormObject                 `json:"metadata,omitempty"`
	Producer         string                          `json:"producer"`
	SchemaVersion    ArtifactDescriptorSchemaVersion `json:"schema_version"`
	Sha256           string                          `json:"sha256"`
	SizeBytes        int64                           `json:"size_bytes"`
	StorageVersion   string                          `json:"storage_version"`
	TrainingRunId    *string                         `json:"training_run_id,omitempty"`
	Uri              string                          `json:"uri"`
	VerifiedAt       *time.Time                      `json:"verified_at,omitempty"`
}

// ArtifactDescriptorSchemaVersion defines model for ArtifactDescriptor.SchemaVersion.
type ArtifactDescriptorSchemaVersion int

// ClaimResult defines model for ClaimResult.
type ClaimResult struct {
	AttemptId      *openapi_types.UUID    `json:"attempt_id,omitempty"`
	Disposition    ClaimResultDisposition `json:"disposition"`
	ExecutionEpoch *int64                 `json:"execution_epoch,omitempty"`
	JobId          openapi_types.UUID     `json:"job_id"`
	LeaseExpiresAt *time.Time             `json:"lease_expires_at,omitempty"`
	Payload        *FreeFormObject        `json:"payload,omitempty"`
	TrainingRunId  *openapi_types.UUID    `json:"training_run_id,omitempty"`
}

// ClaimResultDisposition defines model for ClaimResult.Disposition.
type ClaimResultDisposition string

// ClaimTrainingJob defines model for ClaimTrainingJob.
type ClaimTrainingJob struct {
	DispatchGeneration int64  `json:"dispatch_generation"`
	WorkerId           string `json:"worker_id"`
}

// CompleteResult defines model for CompleteResult.
type CompleteResult struct {
	JobId          openapi_types.UUID `json:"job_id"`
	Metrics        FreeFormObject     `json:"metrics"`
	ModelVersionId openapi_types.UUID `json:"model_version_id"`
	TrainingRunId  openapi_types.UUID `json:"training_run_id"`
}

// CompleteTrainingJob defines model for CompleteTrainingJob.
type CompleteTrainingJob struct {
	Artifacts      []ArtifactDescriptor `json:"artifacts"`
	AttemptId      openapi_types.UUID   `json:"attempt_id"`
	CompletionKey  string               `json:"completion_key"`
	ExecutionEpoch int64                `json:"execution_epoch"`
	Metrics        *FreeFormObject      `json:"metrics,omitempty"`
	ResultDigest   string               `json:"result_digest"`
}

// CreateTrainingRun defines model for CreateTrainingRun.
type CreateTrainingRun struct {
	BackboneId          *string                       `json:"backbone_id,omitempty"`
	DatasetId           *string                       `json:"dataset_id,omitempty"`
	DatasetVersionId    string                        `json:"dataset_version_id"`
	Extractor           *CreateTrainingRunExtractor   `json:"extractor,omitempty"`
	ExtractorConfig     *FreeFormObject               `json:"extractor_config,omitempty"`
	FeatureBatchSize    *int                          `json:"feature_batch_size,omitempty"`
	FeaturePool         *CreateTrainingRunFeaturePool `json:"feature_pool,omitempty"`
	HeadConfig          *FreeFormObject               `json:"head_config,omitempty"`
	ImageSize           *int                          `json:"image_size,omitempty"`
	MaxAttempts         *int                          `json:"max_attempts,omitempty"`
	ReviewCostPerItem   *float32                      `json:"review_cost_per_item,omitempty"`
	TargetSelectiveRisk *float32                      `json:"target_selective_risk,omitempty"`
}

// CreateTrainingRunExtractor defines model for CreateTrainingRun.Extractor.
type CreateTrainingRunExtractor string

// CreateTrainingRunFeaturePool defines model for CreateTrainingRun.FeaturePool.
type CreateTrainingRunFeaturePool string

// DatasetEnvelope defines model for DatasetEnvelope.
type DatasetEnvelope struct {
	Dataset FreeFormObject `json:"dataset"`
}

// Error defines model for Error.
type Error struct {
	Code      string         `json:"code"`
	Details   FreeFormObject `json:"details"`
	Message   string         `json:"message"`
	RequestId string         `json:"request_id"`
}

// ErrorEnvelope defines model for ErrorEnvelope.
type ErrorEnvelope struct {
	Error Error `json:"error"`
}

// FailTrainingJob defines model for FailTrainingJob.
type FailTrainingJob struct {
	AttemptId      openapi_types.UUID `json:"attempt_id"`
	ErrorCode      string             `json:"error_code"`
	ErrorMessage   string             `json:"error_message"`
	ExecutionEpoch int64              `json:"execution_epoch"`
	Retryable      bool               `json:"retryable"`
}

// FencedCommand defines model for FencedCommand.
type FencedCommand struct {
	AttemptId      openapi_types.UUID `json:"attempt_id"`
	ExecutionEpoch int64              `json:"execution_epoch"`
}

// FreeFormObject defines model for FreeFormObject.
type FreeFormObject map[string]interface{}

// Health defines model for Health.
type Health struct {
	Runtime HealthRuntime `json:"runtime"`
	Status  HealthStatus  `json:"status"`
}

// HealthRuntime defines model for Health.Runtime.
type HealthRuntime string

// HealthStatus defines model for Health.Status.
type HealthStatus string

// HeartbeatResult defines model for HeartbeatResult.
type HeartbeatResult struct {
	Directive      HeartbeatResultDirective `json:"directive"`
	LeaseExpiresAt time.Time                `json:"lease_expires_at"`
}

// HeartbeatResultDirective defines model for HeartbeatResult.Directive.
type HeartbeatResultDirective string

// JobEnvelope defines model for JobEnvelope.
type JobEnvelope struct {
	Job FreeFormObject `json:"job"`
}

// LLMAssistanceEnvelope defines model for LLMAssistanceEnvelope.
type LLMAssistanceEnvelope struct {
	Assistance FreeFormObject `json:"assistance"`
}

// LLMAssistanceRequest defines model for LLMAssistanceRequest.
type LLMAssistanceRequest struct {
	Context FreeFormObject           `json:"context"`
	Task    LLMAssistanceRequestTask `json:"task"`
}

// LLMAssistanceRequestTask defines model for LLMAssistanceRequest.Task.
type LLMAssistanceRequestTask string

// TrainingRunEnvelope defines model for TrainingRunEnvelope.
type TrainingRunEnvelope struct {
	TrainingRun FreeFormObject `json:"training_run"`
}

// DatasetID defines model for DatasetID.
type DatasetID = string

// JobID defines model for JobID.
type JobID = openapi_types.UUID

// RunID defines model for RunID.
type RunID = openapi_types.UUID

// ClaimResponse defines model for ClaimResponse.
type ClaimResponse = ClaimResult

// CompleteResponse defines model for CompleteResponse.
type CompleteResponse = CompleteResult

// DatasetResponse defines model for DatasetResponse.
type DatasetResponse = DatasetEnvelope

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse = ErrorEnvelope

// HeartbeatResponse defines model for HeartbeatResponse.
type HeartbeatResponse = HeartbeatResult

// JobResponse defines model for JobResponse.
type JobResponse = JobEnvelope

// LLMAssistanceResponse defines model for LLMAssistanceResponse.
type LLMAssistanceResponse = LLMAssistanceEnvelope

// TrainingRunResponse defines model for TrainingRunResponse.
type TrainingRunResponse = TrainingRunEnvelope

// ReportTrainingProgressJSONBody defines parameters for ReportTrainingProgress.
type ReportTrainingProgressJSONBody struct {
	AttemptId      openapi_types.UUID `json:"attempt_id"`
	ExecutionEpoch int64              `json:"execution_epoch"`
	Progress       FreeFormObject     `json:"progress"`
}

// GenerateLLMAssistanceJSONRequestBody defines body for GenerateLLMAssistance for application/json ContentType.
type GenerateLLMAssistanceJSONRequestBody = LLMAssistanceRequest

// CreateTrainingRunJSONRequestBody defines body for CreateTrainingRun for application/json ContentType.
type CreateTrainingRunJSONRequestBody = CreateTrainingRun

// ClaimTrainingJobJSONRequestBody defines body for ClaimTrainingJob for application/json ContentType.
type ClaimTrainingJobJSONRequestBody = ClaimTrainingJob

// CompleteTrainingJobJSONRequestBody defines body for CompleteTrainingJob for application/json ContentType.
type CompleteTrainingJobJSONRequestBody = CompleteTrainingJob

// FailTrainingJobJSONRequestBody defines body for FailTrainingJob for application/json ContentType.
type FailTrainingJobJSONRequestBody = FailTrainingJob

// HeartbeatTrainingJobJSONRequestBody defines body for HeartbeatTrainingJob for application/json ContentType.
type HeartbeatTrainingJobJSONRequestBody = FencedCommand

// ReportTrainingProgressJSONRequestBody defines body for ReportTrainingProgress for application/json ContentType.
type ReportTrainingProgressJSONRequestBody ReportTrainingProgressJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /api/datasets)
	ListDatasets(w http.ResponseWriter, r *http.Request)

	// (GET /api/datasets/{dataset_id})
	GetDataset(w http.ResponseWriter, r *http.Request, datasetId DatasetID)

	// (GET /api/health)
	GetHealth(w http.ResponseWriter, r *http.Request)

	// (GET /api/jobs)
	ListJobs(w http.ResponseWriter, r *http.Request)

	// (GET /api/jobs/{job_id})
	GetJob(w http.ResponseWriter, r *http.Request, jobId JobID)

	// (POST /api/llm/assist)
	GenerateLLMAssistance(w http.ResponseWriter, r *http.Request)

	// (GET /api/model-weights)
	ListModelWeights(w http.ResponseWriter, r *http.Request)

	// (DELETE /api/model-weights/{preset})
	EvictModelWeightCache(w http.ResponseWriter, r *http.Request, preset string)

	// (GET /api/training-runs)
	ListTrainingRuns(w http.ResponseWriter, r *http.Request)

	// (POST /api/training-runs)
	CreateTrainingRun(w http.ResponseWriter, r *http.Request)

	// (GET /api/training-runs/{run_id})
	GetTrainingRun(w http.ResponseWriter, r *http.Request, runId RunID)

	// (POST /api/training-runs/{run_id}/cancel)
	CancelTrainingRun(w http.ResponseWriter, r *http.Request, runId RunID)

	// (POST /api/training-runs/{run_id}/pause)
	PauseTrainingRun(w http.ResponseWriter, r *http.Request, runId RunID)

	// (POST /api/training-runs/{run_id}/resume)
	ResumeTrainingRun(w http.ResponseWriter, r *http.Request, runId RunID)

	// (POST /internal/training-jobs/{job_id}/claim)
	ClaimTrainingJob(w http.ResponseWriter, r *http.Request, jobId JobID)

	// (POST /internal/training-jobs/{job_id}/complete)
	CompleteTrainingJob(w http.ResponseWriter, r *http.Request, jobId JobID)

	// (POST /internal/training-jobs/{job_id}/fail)
	FailTrainingJob(w http.ResponseWriter, r *http.Request, jobId JobID)

	// (POST /internal/training-jobs/{job_id}/heartbeat)
	HeartbeatTrainingJob(w http.ResponseWriter, r *http.Request, jobId JobID)

	// (POST /internal/training-jobs/{job_id}/progress)
	ReportTrainingProgress(w http.ResponseWriter, r *http.Request, jobId JobID)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// (GET /api/datasets)
func (_ Unimplemented) ListDatasets(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /api/datasets/{dataset_id})
func (_ Unimplemented) GetDataset(w http.ResponseWriter, r *http.Request, datasetId DatasetID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /api/health)
func (_ Unimplemented) GetHealth(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /api/jobs)
func (_ Unimplemented) ListJobs(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /api/jobs/{job_id})
func (_ Unimplemented) GetJob(w http.ResponseWriter, r *http.Request, jobId JobID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /api/llm/assist)
func (_ Unimplemented) GenerateLLMAssistance(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /api/model-weights)
func (_ Unimplemented) ListModelWeights(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (DELETE /api/model-weights/{preset})
func (_ Unimplemented) EvictModelWeightCache(w http.ResponseWriter, r *http.Request, preset string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /api/training-runs)
func (_ Unimplemented) ListTrainingRuns(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /api/training-runs)
func (_ Unimplemented) CreateTrainingRun(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /api/training-runs/{run_id})
func (_ Unimplemented) GetTrainingRun(w http.ResponseWriter, r *http.Request, runId RunID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /api/training-runs/{run_id}/cancel)
func (_ Unimplemented) CancelTrainingRun(w http.ResponseWriter, r *http.Request, runId RunID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /api/training-runs/{run_id}/pause)
func (_ Unimplemented) PauseTrainingRun(w http.ResponseWriter, r *http.Request, runId RunID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /api/training-runs/{run_id}/resume)
func (_ Unimplemented) ResumeTrainingRun(w http.ResponseWriter, r *http.Request, runId RunID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /internal/training-jobs/{job_id}/claim)
func (_ Unimplemented) ClaimTrainingJob(w http.ResponseWriter, r *http.Request, jobId JobID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /internal/training-jobs/{job_id}/complete)
func (_ Unimplemented) CompleteTrainingJob(w http.ResponseWriter, r *http.Request, jobId JobID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /internal/training-jobs/{job_id}/fail)
func (_ Unimplemented) FailTrainingJob(w http.ResponseWriter, r *http.Request, jobId JobID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /internal/training-jobs/{job_id}/heartbeat)
func (_ Unimplemented) HeartbeatTrainingJob(w http.ResponseWriter, r *http.Request, jobId JobID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /internal/training-jobs/{job_id}/progress)
func (_ Unimplemented) ReportTrainingProgress(w http.ResponseWriter, r *http.Request, jobId JobID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListDatasets operation middleware
func (siw *ServerInterfaceWrapper) ListDatasets(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListDatasets(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetDataset operation middleware
func (siw *ServerInterfaceWrapper) GetDataset(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "dataset_id" -------------
	var datasetId DatasetID

	err = runtime.BindStyledParameterWithOptions("simple", "dataset_id", chi.URLParam(r, "dataset_id"), &datasetId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "dataset_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetDataset(w, r, datasetId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListJobs operation middleware
func (siw *ServerInterfaceWrapper) ListJobs(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListJobs(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetJob operation middleware
func (siw *ServerInterfaceWrapper) GetJob(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "job_id" -------------
	var jobId JobID

	err = runtime.BindStyledParameterWithOptions("simple", "job_id", chi.URLParam(r, "job_id"), &jobId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "job_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetJob(w, r, jobId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GenerateLLMAssistance operation middleware
func (siw *ServerInterfaceWrapper) GenerateLLMAssistance(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GenerateLLMAssistance(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListModelWeights operation middleware
func (siw *ServerInterfaceWrapper) ListModelWeights(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListModelWeights(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// EvictModelWeightCache operation middleware
func (siw *ServerInterfaceWrapper) EvictModelWeightCache(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "preset" -------------
	var preset string

	err = runtime.BindStyledParameterWithOptions("simple", "preset", chi.URLParam(r, "preset"), &preset, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "preset", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.EvictModelWeightCache(w, r, preset)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListTrainingRuns operation middleware
func (siw *ServerInterfaceWrapper) ListTrainingRuns(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListTrainingRuns(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateTrainingRun operation middleware
func (siw *ServerInterfaceWrapper) CreateTrainingRun(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateTrainingRun(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetTrainingRun operation middleware
func (siw *ServerInterfaceWrapper) GetTrainingRun(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "run_id" -------------
	var runId RunID

	err = runtime.BindStyledParameterWithOptions("simple", "run_id", chi.URLParam(r, "run_id"), &runId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "run_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetTrainingRun(w, r, runId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CancelTrainingRun operation middleware
func (siw *ServerInterfaceWrapper) CancelTrainingRun(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "run_id" -------------
	var runId RunID

	err = runtime.BindStyledParameterWithOptions("simple", "run_id", chi.URLParam(r, "run_id"), &runId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "run_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CancelTrainingRun(w, r, runId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PauseTrainingRun operation middleware
func (siw *ServerInterfaceWrapper) PauseTrainingRun(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "run_id" -------------
	var runId RunID

	err = runtime.BindStyledParameterWithOptions("simple", "run_id", chi.URLParam(r, "run_id"), &runId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "run_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PauseTrainingRun(w, r, runId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ResumeTrainingRun operation middleware
func (siw *ServerInterfaceWrapper) ResumeTrainingRun(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "run_id" -------------
	var runId RunID

	err = runtime.BindStyledParameterWithOptions("simple", "run_id", chi.URLParam(r, "run_id"), &runId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "run_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ResumeTrainingRun(w, r, runId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ClaimTrainingJob operation middleware
func (siw *ServerInterfaceWrapper) ClaimTrainingJob(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "job_id" -------------
	var jobId JobID

	err = runtime.BindStyledParameterWithOptions("simple", "job_id", chi.URLParam(r, "job_id"), &jobId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "job_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ClaimTrainingJob(w, r, jobId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CompleteTrainingJob operation middleware
func (siw *ServerInterfaceWrapper) CompleteTrainingJob(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "job_id" -------------
	var jobId JobID

	err = runtime.BindStyledParameterWithOptions("simple", "job_id", chi.URLParam(r, "job_id"), &jobId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "job_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CompleteTrainingJob(w, r, jobId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// FailTrainingJob operation middleware
func (siw *ServerInterfaceWrapper) FailTrainingJob(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "job_id" -------------
	var jobId JobID

	err = runtime.BindStyledParameterWithOptions("simple", "job_id", chi.URLParam(r, "job_id"), &jobId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "job_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.FailTrainingJob(w, r, jobId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// HeartbeatTrainingJob operation middleware
func (siw *ServerInterfaceWrapper) HeartbeatTrainingJob(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "job_id" -------------
	var jobId JobID

	err = runtime.BindStyledParameterWithOptions("simple", "job_id", chi.URLParam(r, "job_id"), &jobId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "job_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.HeartbeatTrainingJob(w, r, jobId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ReportTrainingProgress operation middleware
func (siw *ServerInterfaceWrapper) ReportTrainingProgress(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "job_id" -------------
	var jobId JobID

	err = runtime.BindStyledParameterWithOptions("simple", "job_id", chi.URLParam(r, "job_id"), &jobId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "job_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ReportTrainingProgress(w, r, jobId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/health", wrapper.GetHealth)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/datasets", wrapper.ListDatasets)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/datasets/{dataset_id}", wrapper.GetDataset)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/jobs", wrapper.ListJobs)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/jobs/{job_id}", wrapper.GetJob)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/model-weights", wrapper.ListModelWeights)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/api/model-weights/{preset}", wrapper.EvictModelWeightCache)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/llm/assist", wrapper.GenerateLLMAssistance)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/training-runs", wrapper.ListTrainingRuns)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/training-runs", wrapper.CreateTrainingRun)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/training-runs/{run_id}", wrapper.GetTrainingRun)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/training-runs/{run_id}/pause", wrapper.PauseTrainingRun)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/training-runs/{run_id}/resume", wrapper.ResumeTrainingRun)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/training-runs/{run_id}/cancel", wrapper.CancelTrainingRun)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/internal/training-jobs/{job_id}/claim", wrapper.ClaimTrainingJob)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/internal/training-jobs/{job_id}/heartbeat", wrapper.HeartbeatTrainingJob)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/internal/training-jobs/{job_id}/progress", wrapper.ReportTrainingProgress)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/internal/training-jobs/{job_id}/complete", wrapper.CompleteTrainingJob)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/internal/training-jobs/{job_id}/fail", wrapper.FailTrainingJob)
	})

	return r
}

type ClaimResponseJSONResponse ClaimResult

type CompleteResponseJSONResponse CompleteResult

type DatasetResponseJSONResponse DatasetEnvelope

type ErrorResponseJSONResponse ErrorEnvelope

type HeartbeatResponseJSONResponse HeartbeatResult

type JobResponseJSONResponse JobEnvelope

type LLMAssistanceResponseJSONResponse LLMAssistanceEnvelope

type TrainingRunResponseJSONResponse TrainingRunEnvelope

type ListDatasetsRequestObject struct {
}

type ListDatasetsResponseObject interface {
	VisitListDatasetsResponse(w http.ResponseWriter) error
}

type ListDatasets200JSONResponse struct {
	Datasets []FreeFormObject `json:"datasets"`
}

func (response ListDatasets200JSONResponse) VisitListDatasetsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetDatasetRequestObject struct {
	DatasetId DatasetID `json:"dataset_id"`
}

type GetDatasetResponseObject interface {
	VisitGetDatasetResponse(w http.ResponseWriter) error
}

type GetDataset200JSONResponse struct{ DatasetResponseJSONResponse }

func (response GetDataset200JSONResponse) VisitGetDatasetResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetDataset404JSONResponse struct{ ErrorResponseJSONResponse }

func (response GetDataset404JSONResponse) VisitGetDatasetResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetHealthRequestObject struct {
}

type GetHealthResponseObject interface {
	VisitGetHealthResponse(w http.ResponseWriter) error
}

type GetHealth200JSONResponse Health

func (response GetHealth200JSONResponse) VisitGetHealthResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListJobsRequestObject struct {
}

type ListJobsResponseObject interface {
	VisitListJobsResponse(w http.ResponseWriter) error
}

type ListJobs200JSONResponse struct {
	Jobs []FreeFormObject `json:"jobs"`
}

func (response ListJobs200JSONResponse) VisitListJobsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetJobRequestObject struct {
	JobId JobID `json:"job_id"`
}

type GetJobResponseObject interface {
	VisitGetJobResponse(w http.ResponseWriter) error
}

type GetJob200JSONResponse struct{ JobResponseJSONResponse }

func (response GetJob200JSONResponse) VisitGetJobResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetJob404JSONResponse struct{ ErrorResponseJSONResponse }

func (response GetJob404JSONResponse) VisitGetJobResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GenerateLLMAssistanceRequestObject struct {
	Body *GenerateLLMAssistanceJSONRequestBody
}

type GenerateLLMAssistanceResponseObject interface {
	VisitGenerateLLMAssistanceResponse(w http.ResponseWriter) error
}

type GenerateLLMAssistance200JSONResponse struct {
	LLMAssistanceResponseJSONResponse
}

func (response GenerateLLMAssistance200JSONResponse) VisitGenerateLLMAssistanceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GenerateLLMAssistance422JSONResponse struct{ ErrorResponseJSONResponse }

func (response GenerateLLMAssistance422JSONResponse) VisitGenerateLLMAssistanceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(422)
	_, err := buf.WriteTo(w)
	return err
}

type GenerateLLMAssistance503JSONResponse ErrorEnvelope

func (response GenerateLLMAssistance503JSONResponse) VisitGenerateLLMAssistanceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type ListModelWeightsRequestObject struct {
}

type ListModelWeightsResponseObject interface {
	VisitListModelWeightsResponse(w http.ResponseWriter) error
}

type ListModelWeights200JSONResponse struct {
	Weights []FreeFormObject `json:"weights"`
}

func (response ListModelWeights200JSONResponse) VisitListModelWeightsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type EvictModelWeightCacheRequestObject struct {
	Preset string `json:"preset"`
}

type EvictModelWeightCacheResponseObject interface {
	VisitEvictModelWeightCacheResponse(w http.ResponseWriter) error
}

type EvictModelWeightCache200JSONResponse FreeFormObject

func (response EvictModelWeightCache200JSONResponse) VisitEvictModelWeightCacheResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type EvictModelWeightCache404JSONResponse struct{ ErrorResponseJSONResponse }

func (response EvictModelWeightCache404JSONResponse) VisitEvictModelWeightCacheResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type ListTrainingRunsRequestObject struct {
}

type ListTrainingRunsResponseObject interface {
	VisitListTrainingRunsResponse(w http.ResponseWriter) error
}

type ListTrainingRuns200JSONResponse struct {
	TrainingRuns []FreeFormObject `json:"training_runs"`
}

func (response ListTrainingRuns200JSONResponse) VisitListTrainingRunsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type CreateTrainingRunRequestObject struct {
	Body *CreateTrainingRunJSONRequestBody
}

type CreateTrainingRunResponseObject interface {
	VisitCreateTrainingRunResponse(w http.ResponseWriter) error
}

type CreateTrainingRun202JSONResponse struct {
	TrainingRunResponseJSONResponse
}

func (response CreateTrainingRun202JSONResponse) VisitCreateTrainingRunResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(202)
	_, err := buf.WriteTo(w)
	return err
}

type CreateTrainingRun422JSONResponse struct{ ErrorResponseJSONResponse }

func (response CreateTrainingRun422JSONResponse) VisitCreateTrainingRunResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(422)
	_, err := buf.WriteTo(w)
	return err
}

type GetTrainingRunRequestObject struct {
	RunId RunID `json:"run_id"`
}

type GetTrainingRunResponseObject interface {
	VisitGetTrainingRunResponse(w http.ResponseWriter) error
}

type GetTrainingRun200JSONResponse struct {
	TrainingRunResponseJSONResponse
}

func (response GetTrainingRun200JSONResponse) VisitGetTrainingRunResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetTrainingRun404JSONResponse struct{ ErrorResponseJSONResponse }

func (response GetTrainingRun404JSONResponse) VisitGetTrainingRunResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type CancelTrainingRunRequestObject struct {
	RunId RunID `json:"run_id"`
}

type CancelTrainingRunResponseObject interface {
	VisitCancelTrainingRunResponse(w http.ResponseWriter) error
}

type CancelTrainingRun200JSONResponse struct {
	TrainingRunResponseJSONResponse
}

func (response CancelTrainingRun200JSONResponse) VisitCancelTrainingRunResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type CancelTrainingRun404JSONResponse struct{ ErrorResponseJSONResponse }

func (response CancelTrainingRun404JSONResponse) VisitCancelTrainingRunResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type CancelTrainingRun409JSONResponse ErrorEnvelope

func (response CancelTrainingRun409JSONResponse) VisitCancelTrainingRunResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type PauseTrainingRunRequestObject struct {
	RunId RunID `json:"run_id"`
}

type PauseTrainingRunResponseObject interface {
	VisitPauseTrainingRunResponse(w http.ResponseWriter) error
}

type PauseTrainingRun200JSONResponse struct {
	TrainingRunResponseJSONResponse
}

func (response PauseTrainingRun200JSONResponse) VisitPauseTrainingRunResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type PauseTrainingRun404JSONResponse struct{ ErrorResponseJSONResponse }

func (response PauseTrainingRun404JSONResponse) VisitPauseTrainingRunResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type PauseTrainingRun409JSONResponse ErrorEnvelope

func (response PauseTrainingRun409JSONResponse) VisitPauseTrainingRunResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type ResumeTrainingRunRequestObject struct {
	RunId RunID `json:"run_id"`
}

type ResumeTrainingRunResponseObject interface {
	VisitResumeTrainingRunResponse(w http.ResponseWriter) error
}

type ResumeTrainingRun200JSONResponse struct {
	TrainingRunResponseJSONResponse
}

func (response ResumeTrainingRun200JSONResponse) VisitResumeTrainingRunResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ResumeTrainingRun404JSONResponse struct{ ErrorResponseJSONResponse }

func (response ResumeTrainingRun404JSONResponse) VisitResumeTrainingRunResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type ResumeTrainingRun409JSONResponse ErrorEnvelope

func (response ResumeTrainingRun409JSONResponse) VisitResumeTrainingRunResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type ClaimTrainingJobRequestObject struct {
	JobId JobID `json:"job_id"`
	Body  *ClaimTrainingJobJSONRequestBody
}

type ClaimTrainingJobResponseObject interface {
	VisitClaimTrainingJobResponse(w http.ResponseWriter) error
}

type ClaimTrainingJob200JSONResponse struct{ ClaimResponseJSONResponse }

func (response ClaimTrainingJob200JSONResponse) VisitClaimTrainingJobResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ClaimTrainingJob404JSONResponse struct{ ErrorResponseJSONResponse }

func (response ClaimTrainingJob404JSONResponse) VisitClaimTrainingJobResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type ClaimTrainingJob409JSONResponse ErrorEnvelope

func (response ClaimTrainingJob409JSONResponse) VisitClaimTrainingJobResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type CompleteTrainingJobRequestObject struct {
	JobId JobID `json:"job_id"`
	Body  *CompleteTrainingJobJSONRequestBody
}

type CompleteTrainingJobResponseObject interface {
	VisitCompleteTrainingJobResponse(w http.ResponseWriter) error
}

type CompleteTrainingJob200JSONResponse struct{ CompleteResponseJSONResponse }

func (response CompleteTrainingJob200JSONResponse) VisitCompleteTrainingJobResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type CompleteTrainingJob404JSONResponse struct{ ErrorResponseJSONResponse }

func (response CompleteTrainingJob404JSONResponse) VisitCompleteTrainingJobResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type CompleteTrainingJob409JSONResponse ErrorEnvelope

func (response CompleteTrainingJob409JSONResponse) VisitCompleteTrainingJobResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type CompleteTrainingJob422JSONResponse ErrorEnvelope

func (response CompleteTrainingJob422JSONResponse) VisitCompleteTrainingJobResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(422)
	_, err := buf.WriteTo(w)
	return err
}

type FailTrainingJobRequestObject struct {
	JobId JobID `json:"job_id"`
	Body  *FailTrainingJobJSONRequestBody
}

type FailTrainingJobResponseObject interface {
	VisitFailTrainingJobResponse(w http.ResponseWriter) error
}

type FailTrainingJob204Response struct {
}

func (response FailTrainingJob204Response) VisitFailTrainingJobResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type FailTrainingJob404JSONResponse struct{ ErrorResponseJSONResponse }

func (response FailTrainingJob404JSONResponse) VisitFailTrainingJobResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type FailTrainingJob409JSONResponse ErrorEnvelope

func (response FailTrainingJob409JSONResponse) VisitFailTrainingJobResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type HeartbeatTrainingJobRequestObject struct {
	JobId JobID `json:"job_id"`
	Body  *HeartbeatTrainingJobJSONRequestBody
}

type HeartbeatTrainingJobResponseObject interface {
	VisitHeartbeatTrainingJobResponse(w http.ResponseWriter) error
}

type HeartbeatTrainingJob200JSONResponse struct{ HeartbeatResponseJSONResponse }

func (response HeartbeatTrainingJob200JSONResponse) VisitHeartbeatTrainingJobResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type HeartbeatTrainingJob404JSONResponse struct{ ErrorResponseJSONResponse }

func (response HeartbeatTrainingJob404JSONResponse) VisitHeartbeatTrainingJobResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type HeartbeatTrainingJob409JSONResponse ErrorEnvelope

func (response HeartbeatTrainingJob409JSONResponse) VisitHeartbeatTrainingJobResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type ReportTrainingProgressRequestObject struct {
	JobId JobID `json:"job_id"`
	Body  *ReportTrainingProgressJSONRequestBody
}

type ReportTrainingProgressResponseObject interface {
	VisitReportTrainingProgressResponse(w http.ResponseWriter) error
}

type ReportTrainingProgress204Response struct {
}

func (response ReportTrainingProgress204Response) VisitReportTrainingProgressResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type ReportTrainingProgress404JSONResponse struct{ ErrorResponseJSONResponse }

func (response ReportTrainingProgress404JSONResponse) VisitReportTrainingProgressResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type ReportTrainingProgress409JSONResponse ErrorEnvelope

func (response ReportTrainingProgress409JSONResponse) VisitReportTrainingProgressResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {

	// (GET /api/datasets)
	ListDatasets(ctx context.Context, request ListDatasetsRequestObject) (ListDatasetsResponseObject, error)

	// (GET /api/datasets/{dataset_id})
	GetDataset(ctx context.Context, request GetDatasetRequestObject) (GetDatasetResponseObject, error)

	// (GET /api/health)
	GetHealth(ctx context.Context, request GetHealthRequestObject) (GetHealthResponseObject, error)

	// (GET /api/jobs)
	ListJobs(ctx context.Context, request ListJobsRequestObject) (ListJobsResponseObject, error)

	// (GET /api/jobs/{job_id})
	GetJob(ctx context.Context, request GetJobRequestObject) (GetJobResponseObject, error)

	// (POST /api/llm/assist)
	GenerateLLMAssistance(ctx context.Context, request GenerateLLMAssistanceRequestObject) (GenerateLLMAssistanceResponseObject, error)

	// (GET /api/model-weights)
	ListModelWeights(ctx context.Context, request ListModelWeightsRequestObject) (ListModelWeightsResponseObject, error)

	// (DELETE /api/model-weights/{preset})
	EvictModelWeightCache(ctx context.Context, request EvictModelWeightCacheRequestObject) (EvictModelWeightCacheResponseObject, error)

	// (GET /api/training-runs)
	ListTrainingRuns(ctx context.Context, request ListTrainingRunsRequestObject) (ListTrainingRunsResponseObject, error)

	// (POST /api/training-runs)
	CreateTrainingRun(ctx context.Context, request CreateTrainingRunRequestObject) (CreateTrainingRunResponseObject, error)

	// (GET /api/training-runs/{run_id})
	GetTrainingRun(ctx context.Context, request GetTrainingRunRequestObject) (GetTrainingRunResponseObject, error)

	// (POST /api/training-runs/{run_id}/cancel)
	CancelTrainingRun(ctx context.Context, request CancelTrainingRunRequestObject) (CancelTrainingRunResponseObject, error)

	// (POST /api/training-runs/{run_id}/pause)
	PauseTrainingRun(ctx context.Context, request PauseTrainingRunRequestObject) (PauseTrainingRunResponseObject, error)

	// (POST /api/training-runs/{run_id}/resume)
	ResumeTrainingRun(ctx context.Context, request ResumeTrainingRunRequestObject) (ResumeTrainingRunResponseObject, error)

	// (POST /internal/training-jobs/{job_id}/claim)
	ClaimTrainingJob(ctx context.Context, request ClaimTrainingJobRequestObject) (ClaimTrainingJobResponseObject, error)

	// (POST /internal/training-jobs/{job_id}/complete)
	CompleteTrainingJob(ctx context.Context, request CompleteTrainingJobRequestObject) (CompleteTrainingJobResponseObject, error)

	// (POST /internal/training-jobs/{job_id}/fail)
	FailTrainingJob(ctx context.Context, request FailTrainingJobRequestObject) (FailTrainingJobResponseObject, error)

	// (POST /internal/training-jobs/{job_id}/heartbeat)
	HeartbeatTrainingJob(ctx context.Context, request HeartbeatTrainingJobRequestObject) (HeartbeatTrainingJobResponseObject, error)

	// (POST /internal/training-jobs/{job_id}/progress)
	ReportTrainingProgress(ctx context.Context, request ReportTrainingProgressRequestObject) (ReportTrainingProgressResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// ListDatasets operation middleware
func (sh *strictHandler) ListDatasets(w http.ResponseWriter, r *http.Request) {
	var request ListDatasetsRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListDatasets(ctx, request.(ListDatasetsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListDatasets")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListDatasetsResponseObject); ok {
		if err := validResponse.VisitListDatasetsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetDataset operation middleware
func (sh *strictHandler) GetDataset(w http.ResponseWriter, r *http.Request, datasetId DatasetID) {
	var request GetDatasetRequestObject

	request.DatasetId = datasetId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetDataset(ctx, request.(GetDatasetRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetDataset")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetDatasetResponseObject); ok {
		if err := validResponse.VisitGetDatasetResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetHealth operation middleware
func (sh *strictHandler) GetHealth(w http.ResponseWriter, r *http.Request) {
	var request GetHealthRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetHealth(ctx, request.(GetHealthRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetHealth")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetHealthResponseObject); ok {
		if err := validResponse.VisitGetHealthResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListJobs operation middleware
func (sh *strictHandler) ListJobs(w http.ResponseWriter, r *http.Request) {
	var request ListJobsRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListJobs(ctx, request.(ListJobsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListJobs")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListJobsResponseObject); ok {
		if err := validResponse.VisitListJobsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetJob operation middleware
func (sh *strictHandler) GetJob(w http.ResponseWriter, r *http.Request, jobId JobID) {
	var request GetJobRequestObject

	request.JobId = jobId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetJob(ctx, request.(GetJobRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetJob")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetJobResponseObject); ok {
		if err := validResponse.VisitGetJobResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GenerateLLMAssistance operation middleware
func (sh *strictHandler) GenerateLLMAssistance(w http.ResponseWriter, r *http.Request) {
	var request GenerateLLMAssistanceRequestObject

	var body GenerateLLMAssistanceJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GenerateLLMAssistance(ctx, request.(GenerateLLMAssistanceRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GenerateLLMAssistance")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GenerateLLMAssistanceResponseObject); ok {
		if err := validResponse.VisitGenerateLLMAssistanceResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListModelWeights operation middleware
func (sh *strictHandler) ListModelWeights(w http.ResponseWriter, r *http.Request) {
	var request ListModelWeightsRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListModelWeights(ctx, request.(ListModelWeightsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListModelWeights")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListModelWeightsResponseObject); ok {
		if err := validResponse.VisitListModelWeightsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// EvictModelWeightCache operation middleware
func (sh *strictHandler) EvictModelWeightCache(w http.ResponseWriter, r *http.Request, preset string) {
	var request EvictModelWeightCacheRequestObject

	request.Preset = preset

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.EvictModelWeightCache(ctx, request.(EvictModelWeightCacheRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "EvictModelWeightCache")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(EvictModelWeightCacheResponseObject); ok {
		if err := validResponse.VisitEvictModelWeightCacheResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListTrainingRuns operation middleware
func (sh *strictHandler) ListTrainingRuns(w http.ResponseWriter, r *http.Request) {
	var request ListTrainingRunsRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListTrainingRuns(ctx, request.(ListTrainingRunsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListTrainingRuns")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListTrainingRunsResponseObject); ok {
		if err := validResponse.VisitListTrainingRunsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateTrainingRun operation middleware
func (sh *strictHandler) CreateTrainingRun(w http.ResponseWriter, r *http.Request) {
	var request CreateTrainingRunRequestObject

	var body CreateTrainingRunJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateTrainingRun(ctx, request.(CreateTrainingRunRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateTrainingRun")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateTrainingRunResponseObject); ok {
		if err := validResponse.VisitCreateTrainingRunResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetTrainingRun operation middleware
func (sh *strictHandler) GetTrainingRun(w http.ResponseWriter, r *http.Request, runId RunID) {
	var request GetTrainingRunRequestObject

	request.RunId = runId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetTrainingRun(ctx, request.(GetTrainingRunRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetTrainingRun")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetTrainingRunResponseObject); ok {
		if err := validResponse.VisitGetTrainingRunResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CancelTrainingRun operation middleware
func (sh *strictHandler) CancelTrainingRun(w http.ResponseWriter, r *http.Request, runId RunID) {
	var request CancelTrainingRunRequestObject

	request.RunId = runId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CancelTrainingRun(ctx, request.(CancelTrainingRunRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CancelTrainingRun")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CancelTrainingRunResponseObject); ok {
		if err := validResponse.VisitCancelTrainingRunResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PauseTrainingRun operation middleware
func (sh *strictHandler) PauseTrainingRun(w http.ResponseWriter, r *http.Request, runId RunID) {
	var request PauseTrainingRunRequestObject

	request.RunId = runId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PauseTrainingRun(ctx, request.(PauseTrainingRunRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PauseTrainingRun")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PauseTrainingRunResponseObject); ok {
		if err := validResponse.VisitPauseTrainingRunResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ResumeTrainingRun operation middleware
func (sh *strictHandler) ResumeTrainingRun(w http.ResponseWriter, r *http.Request, runId RunID) {
	var request ResumeTrainingRunRequestObject

	request.RunId = runId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ResumeTrainingRun(ctx, request.(ResumeTrainingRunRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ResumeTrainingRun")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ResumeTrainingRunResponseObject); ok {
		if err := validResponse.VisitResumeTrainingRunResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ClaimTrainingJob operation middleware
func (sh *strictHandler) ClaimTrainingJob(w http.ResponseWriter, r *http.Request, jobId JobID) {
	var request ClaimTrainingJobRequestObject

	request.JobId = jobId

	var body ClaimTrainingJobJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ClaimTrainingJob(ctx, request.(ClaimTrainingJobRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ClaimTrainingJob")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ClaimTrainingJobResponseObject); ok {
		if err := validResponse.VisitClaimTrainingJobResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CompleteTrainingJob operation middleware
func (sh *strictHandler) CompleteTrainingJob(w http.ResponseWriter, r *http.Request, jobId JobID) {
	var request CompleteTrainingJobRequestObject

	request.JobId = jobId

	var body CompleteTrainingJobJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CompleteTrainingJob(ctx, request.(CompleteTrainingJobRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CompleteTrainingJob")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CompleteTrainingJobResponseObject); ok {
		if err := validResponse.VisitCompleteTrainingJobResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// FailTrainingJob operation middleware
func (sh *strictHandler) FailTrainingJob(w http.ResponseWriter, r *http.Request, jobId JobID) {
	var request FailTrainingJobRequestObject

	request.JobId = jobId

	var body FailTrainingJobJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.FailTrainingJob(ctx, request.(FailTrainingJobRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "FailTrainingJob")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(FailTrainingJobResponseObject); ok {
		if err := validResponse.VisitFailTrainingJobResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// HeartbeatTrainingJob operation middleware
func (sh *strictHandler) HeartbeatTrainingJob(w http.ResponseWriter, r *http.Request, jobId JobID) {
	var request HeartbeatTrainingJobRequestObject

	request.JobId = jobId

	var body HeartbeatTrainingJobJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.HeartbeatTrainingJob(ctx, request.(HeartbeatTrainingJobRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "HeartbeatTrainingJob")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(HeartbeatTrainingJobResponseObject); ok {
		if err := validResponse.VisitHeartbeatTrainingJobResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ReportTrainingProgress operation middleware
func (sh *strictHandler) ReportTrainingProgress(w http.ResponseWriter, r *http.Request, jobId JobID) {
	var request ReportTrainingProgressRequestObject

	request.JobId = jobId

	var body ReportTrainingProgressJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ReportTrainingProgress(ctx, request.(ReportTrainingProgressRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ReportTrainingProgress")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ReportTrainingProgressResponseObject); ok {
		if err := validResponse.VisitReportTrainingProgressResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}
