from __future__ import annotations

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

metadata = sa.MetaData()

datasets = sa.Table(
    "datasets",
    metadata,
    sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
    sa.Column("dataset_key", sa.Text(), nullable=False, unique=True),
    sa.Column("name", sa.Text(), nullable=False),
    sa.Column("description", sa.Text()),
    sa.Column("domain", sa.Text()),
    sa.Column("status", sa.Text(), nullable=False),
    sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status in ('draft', 'ready', 'archived')", name="ck_datasets_status"),
)

jobs = sa.Table(
    "jobs",
    metadata,
    sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
    sa.Column("job_key", sa.Text(), nullable=False, unique=True),
    sa.Column("job_type", sa.Text(), nullable=False),
    sa.Column("status", sa.Text(), nullable=False),
    sa.Column("payload", postgresql.JSONB(), nullable=False),
    sa.Column("result", postgresql.JSONB()),
    sa.Column("error_message", sa.Text()),
    sa.Column("priority", sa.Integer(), nullable=False, server_default="100"),
    sa.Column("attempt_count", sa.Integer(), nullable=False, server_default="0"),
    sa.Column("max_attempts", sa.Integer(), nullable=False, server_default="3"),
    sa.Column("lease_owner", sa.Text()),
    sa.Column("lease_expires_at", sa.DateTime(timezone=True)),
    sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    sa.Column("queued_at", sa.DateTime(timezone=True), nullable=False),
    sa.Column("started_at", sa.DateTime(timezone=True)),
    sa.Column("finished_at", sa.DateTime(timezone=True)),
    sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint(
        "status in ('queued', 'paused', 'running', 'succeeded', 'failed', 'cancelled')",
        name="ck_jobs_status",
    ),
)

dataset_versions = sa.Table(
    "dataset_versions",
    metadata,
    sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
    sa.Column("dataset_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("datasets.id"), nullable=False),
    sa.Column("version_key", sa.Text(), nullable=False, unique=True),
    sa.Column("root_uri", sa.Text(), nullable=False),
    sa.Column("sample_count", sa.Integer(), nullable=False),
    sa.Column("class_count", sa.Integer(), nullable=False),
    sa.Column("split_summary", postgresql.JSONB(), nullable=False),
    sa.Column("readiness_status", sa.Text(), nullable=False),
    sa.Column("readiness_report", postgresql.JSONB(), nullable=False),
    sa.Column("manifest_artifact_id", postgresql.UUID(as_uuid=True)),
    sa.Column("created_by_job_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("jobs.id")),
    sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
)

artifacts = sa.Table(
    "artifacts",
    metadata,
    sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
    sa.Column("artifact_key", sa.Text(), nullable=False, unique=True),
    sa.Column("artifact_type", sa.Text(), nullable=False),
    sa.Column("dataset_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("datasets.id")),
    sa.Column("dataset_version_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("dataset_versions.id")),
    sa.Column("job_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("jobs.id")),
    sa.Column("uri", sa.Text(), nullable=False),
    sa.Column("checksum", sa.Text()),
    sa.Column("content_type", sa.Text()),
    sa.Column("size_bytes", sa.BigInteger()),
    sa.Column("artifact_metadata", postgresql.JSONB(), nullable=False, server_default=sa.text("'{}'::jsonb")),
    sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
)

job_events = sa.Table(
    "job_events",
    metadata,
    sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
    sa.Column("job_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("jobs.id"), nullable=False),
    sa.Column("event_type", sa.Text(), nullable=False),
    sa.Column("message", sa.Text()),
    sa.Column("payload", postgresql.JSONB(), nullable=False, server_default=sa.text("'{}'::jsonb")),
    sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
)

training_runs = sa.Table(
    "training_runs",
    metadata,
    sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
    sa.Column("run_key", sa.Text(), nullable=False, unique=True),
    sa.Column("job_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("jobs.id"), nullable=False),
    sa.Column("dataset_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("datasets.id"), nullable=False),
    sa.Column("dataset_version_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("dataset_versions.id"), nullable=False),
    sa.Column("status", sa.Text(), nullable=False),
    sa.Column("backbone_id", sa.Text(), nullable=False),
    sa.Column("extractor_config", postgresql.JSONB(), nullable=False),
    sa.Column("head_config", postgresql.JSONB(), nullable=False),
    sa.Column("feature_artifact_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("artifacts.id")),
    sa.Column("model_artifact_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("artifacts.id")),
    sa.Column("report_artifact_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("artifacts.id")),
    sa.Column("calibration_artifact_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("artifacts.id")),
    sa.Column("threshold_strategy_artifact_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("artifacts.id")),
    sa.Column("metrics", postgresql.JSONB(), nullable=False, server_default=sa.text("'{}'::jsonb")),
    sa.Column("error_message", sa.Text()),
    sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    sa.Column("started_at", sa.DateTime(timezone=True)),
    sa.Column("finished_at", sa.DateTime(timezone=True)),
    sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint(
        "status in ('queued', 'paused', 'running', 'succeeded', 'failed', 'cancelled')",
        name="ck_training_runs_status",
    ),
)

model_versions = sa.Table(
    "model_versions",
    metadata,
    sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
    sa.Column("model_key", sa.Text(), nullable=False, unique=True),
    sa.Column("dataset_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("datasets.id"), nullable=False),
    sa.Column("dataset_version_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("dataset_versions.id"), nullable=False),
    sa.Column("training_run_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("training_runs.id"), nullable=False),
    sa.Column("status", sa.Text(), nullable=False),
    sa.Column("model_artifact_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("artifacts.id"), nullable=False),
    sa.Column("calibration_artifact_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("artifacts.id")),
    sa.Column("threshold_strategy_artifact_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("artifacts.id")),
    sa.Column("metrics", postgresql.JSONB(), nullable=False, server_default=sa.text("'{}'::jsonb")),
    sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint(
        "status in ('candidate', 'staging', 'production', 'archived', 'failed')",
        name="ck_model_versions_status",
    ),
)

inference_events = sa.Table(
    "inference_events",
    metadata,
    sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
    sa.Column("event_key", sa.Text(), nullable=False, unique=True),
    sa.Column("dataset_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("datasets.id"), nullable=False),
    sa.Column("dataset_version_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("dataset_versions.id"), nullable=False),
    sa.Column("model_version_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("model_versions.id"), nullable=False),
    sa.Column("model_status", sa.Text(), nullable=False),
    sa.Column("model_artifact_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("artifacts.id")),
    sa.Column("feature_artifact_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("artifacts.id")),
    sa.Column("threshold_strategy_artifact_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("artifacts.id")),
    sa.Column("input_type", sa.Text(), nullable=False),
    sa.Column("input_ref", sa.Text()),
    sa.Column("sample_id", sa.Text()),
    sa.Column("decision", sa.Text(), nullable=False),
    sa.Column("confidence", sa.Float()),
    sa.Column("margin", sa.Float()),
    sa.Column("ood_score", sa.Float()),
    sa.Column("reasons", postgresql.JSONB(), nullable=False, server_default=sa.text("'[]'::jsonb")),
    sa.Column("request_payload", postgresql.JSONB(), nullable=False),
    sa.Column("result_payload", postgresql.JSONB(), nullable=False),
    sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("input_type in ('sample', 'image_path', 'upload')", name="ck_inference_events_input_type"),
    sa.CheckConstraint("decision in ('accept', 'abstain', 'reject_ood')", name="ck_inference_events_decision"),
)

review_items = sa.Table(
    "review_items",
    metadata,
    sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
    sa.Column("review_key", sa.Text(), nullable=False, unique=True),
    sa.Column(
        "inference_event_id",
        postgresql.UUID(as_uuid=True),
        sa.ForeignKey("inference_events.id"),
        nullable=False,
        unique=True,
    ),
    sa.Column("dataset_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("datasets.id"), nullable=False),
    sa.Column("dataset_version_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("dataset_versions.id"), nullable=False),
    sa.Column("model_version_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("model_versions.id"), nullable=False),
    sa.Column("sample_id", sa.Text()),
    sa.Column("input_ref", sa.Text()),
    sa.Column("status", sa.Text(), nullable=False),
    sa.Column("risk_type", sa.Text(), nullable=False),
    sa.Column("priority", sa.Integer(), nullable=False, server_default="100"),
    sa.Column("reason", sa.Text(), nullable=False),
    sa.Column("reason_codes", postgresql.JSONB(), nullable=False, server_default=sa.text("'[]'::jsonb")),
    sa.Column("context", postgresql.JSONB(), nullable=False, server_default=sa.text("'{}'::jsonb")),
    sa.Column("assistance_metadata", postgresql.JSONB(), nullable=False, server_default=sa.text("'{}'::jsonb")),
    sa.Column("assigned_to", sa.Text()),
    sa.Column("submitted_at", sa.DateTime(timezone=True)),
    sa.Column("feedbacked_at", sa.DateTime(timezone=True)),
    sa.Column("completed_by", sa.Text()),
    sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint(
        "status in ('pending', 'submitted', 'feedbacked', 'skipped', 'disputed')",
        name="ck_review_items_status",
    ),
    sa.CheckConstraint(
        "risk_type in ('low_confidence', 'low_margin', 'ood_candidate', 'mixed')",
        name="ck_review_items_risk_type",
    ),
)

feedback_items = sa.Table(
    "feedback_items",
    metadata,
    sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
    sa.Column("feedback_key", sa.Text(), nullable=False, unique=True),
    sa.Column(
        "review_item_id",
        postgresql.UUID(as_uuid=True),
        sa.ForeignKey("review_items.id"),
        nullable=False,
        unique=True,
    ),
    sa.Column("inference_event_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("inference_events.id"), nullable=False),
    sa.Column("dataset_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("datasets.id"), nullable=False),
    sa.Column("dataset_version_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("dataset_versions.id"), nullable=False),
    sa.Column("model_version_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("model_versions.id"), nullable=False),
    sa.Column("sample_id", sa.Text()),
    sa.Column("final_label", sa.Text()),
    sa.Column("final_outcome", sa.Text(), nullable=False),
    sa.Column("destination", sa.Text(), nullable=False),
    sa.Column("reviewer_note", sa.Text()),
    sa.Column("feedback_metadata", postgresql.JSONB(), nullable=False, server_default=sa.text("'{}'::jsonb")),
    sa.Column("created_by", sa.Text()),
    sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint(
        "final_outcome in ('confirmed_label', 'corrected_label', 'ood', 'bad_image', 'uncertain', 'ignore')",
        name="ck_feedback_items_final_outcome",
    ),
    sa.CheckConstraint(
        "destination in ('training_candidate', 'ood_stress', 'bad_image', 'taxonomy_dispute', 'ignore')",
        name="ck_feedback_items_destination",
    ),
)
